/*
 * Customer Reliability
 *  <b>Customer Reliability</b>  
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Address;

/**
 * AddressCustomerSubscription
 */

public class AddressCustomerSubscription {
  @JsonProperty("city")
  private String city = null;

  @JsonProperty("province")
  private String province = null;

  @JsonProperty("nation")
  private String nation = null;

  @JsonProperty("street")
  private String street = null;

  @JsonProperty("streetNumber")
  private String streetNumber = null;

  @JsonProperty("postalCode")
  private String postalCode = null;

  @JsonProperty("addressNationUifCode")
  private String addressNationUifCode = null;

  @JsonProperty("addresNationIsoCode")
  private String addresNationIsoCode = null;

  public AddressCustomerSubscription city(String city) {
    this.city = city;
    return this;
  }

   /**
   * residenceCity
   * @return city
  **/
  @ApiModelProperty(value = "residenceCity")
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public AddressCustomerSubscription province(String province) {
    this.province = province;
    return this;
  }

   /**
   * residenceProvince
   * @return province
  **/
  @ApiModelProperty(value = "residenceProvince")
  public String getProvince() {
    return province;
  }

  public void setProvince(String province) {
    this.province = province;
  }

  public AddressCustomerSubscription nation(String nation) {
    this.nation = nation;
    return this;
  }

   /**
   * residenceNation
   * @return nation
  **/
  @ApiModelProperty(value = "residenceNation")
  public String getNation() {
    return nation;
  }

  public void setNation(String nation) {
    this.nation = nation;
  }

  public AddressCustomerSubscription street(String street) {
    this.street = street;
    return this;
  }

   /**
   * residenceStreet
   * @return street
  **/
  @ApiModelProperty(value = "residenceStreet")
  public String getStreet() {
    return street;
  }

  public void setStreet(String street) {
    this.street = street;
  }

  public AddressCustomerSubscription streetNumber(String streetNumber) {
    this.streetNumber = streetNumber;
    return this;
  }

   /**
   * residenceCivic
   * @return streetNumber
  **/
  @ApiModelProperty(value = "residenceCivic")
  public String getStreetNumber() {
    return streetNumber;
  }

  public void setStreetNumber(String streetNumber) {
    this.streetNumber = streetNumber;
  }

  public AddressCustomerSubscription postalCode(String postalCode) {
    this.postalCode = postalCode;
    return this;
  }

   /**
   * residencePostalCode
   * @return postalCode
  **/
  @ApiModelProperty(value = "residencePostalCode")
  public String getPostalCode() {
    return postalCode;
  }

  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }

  public AddressCustomerSubscription addressNationUifCode(String addressNationUifCode) {
    this.addressNationUifCode = addressNationUifCode;
    return this;
  }

   /**
   * document issuer uic code
   * @return addressNationUifCode
  **/
  @ApiModelProperty(example = "086", value = "document issuer uic code")
  public String getAddressNationUifCode() {
    return addressNationUifCode;
  }

  public void setAddressNationUifCode(String addressNationUifCode) {
    this.addressNationUifCode = addressNationUifCode;
  }

  public AddressCustomerSubscription addresNationIsoCode(String addresNationIsoCode) {
    this.addresNationIsoCode = addresNationIsoCode;
    return this;
  }

   /**
   * document issuer iso code
   * @return addresNationIsoCode
  **/
  @ApiModelProperty(example = "IT", value = "document issuer iso code")
  public String getAddresNationIsoCode() {
    return addresNationIsoCode;
  }

  public void setAddresNationIsoCode(String addresNationIsoCode) {
    this.addresNationIsoCode = addresNationIsoCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddressCustomerSubscription addressCustomerSubscription = (AddressCustomerSubscription) o;
    return Objects.equals(this.city, addressCustomerSubscription.city) &&
        Objects.equals(this.province, addressCustomerSubscription.province) &&
        Objects.equals(this.nation, addressCustomerSubscription.nation) &&
        Objects.equals(this.street, addressCustomerSubscription.street) &&
        Objects.equals(this.streetNumber, addressCustomerSubscription.streetNumber) &&
        Objects.equals(this.postalCode, addressCustomerSubscription.postalCode) &&
        Objects.equals(this.addressNationUifCode, addressCustomerSubscription.addressNationUifCode) &&
        Objects.equals(this.addresNationIsoCode, addressCustomerSubscription.addresNationIsoCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(city, province, nation, street, streetNumber, postalCode, addressNationUifCode, addresNationIsoCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddressCustomerSubscription {\n");
    
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    province: ").append(toIndentedString(province)).append("\n");
    sb.append("    nation: ").append(toIndentedString(nation)).append("\n");
    sb.append("    street: ").append(toIndentedString(street)).append("\n");
    sb.append("    streetNumber: ").append(toIndentedString(streetNumber)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    addressNationUifCode: ").append(toIndentedString(addressNationUifCode)).append("\n");
    sb.append("    addresNationIsoCode: ").append(toIndentedString(addresNationIsoCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

