/*
 * Customer Reliability
 *  <b>Customer Reliability</b>  
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Address;

/**
 * AddressExtended
 */

public class AddressExtended {
  @JsonProperty("city")
  private String city = null;

  @JsonProperty("province")
  private String province = null;

  @JsonProperty("nation")
  private String nation = null;

  @JsonProperty("street")
  private String street = null;

  @JsonProperty("streetNumber")
  private String streetNumber = null;

  @JsonProperty("postalCode")
  private String postalCode = null;

  @JsonProperty("municipality")
  private String municipality = null;

  @JsonProperty("others")
  private String others = null;

  public AddressExtended city(String city) {
    this.city = city;
    return this;
  }

   /**
   * residenceCity
   * @return city
  **/
  @ApiModelProperty(value = "residenceCity")
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public AddressExtended province(String province) {
    this.province = province;
    return this;
  }

   /**
   * residenceProvince
   * @return province
  **/
  @ApiModelProperty(value = "residenceProvince")
  public String getProvince() {
    return province;
  }

  public void setProvince(String province) {
    this.province = province;
  }

  public AddressExtended nation(String nation) {
    this.nation = nation;
    return this;
  }

   /**
   * residenceNation
   * @return nation
  **/
  @ApiModelProperty(value = "residenceNation")
  public String getNation() {
    return nation;
  }

  public void setNation(String nation) {
    this.nation = nation;
  }

  public AddressExtended street(String street) {
    this.street = street;
    return this;
  }

   /**
   * residenceStreet
   * @return street
  **/
  @ApiModelProperty(value = "residenceStreet")
  public String getStreet() {
    return street;
  }

  public void setStreet(String street) {
    this.street = street;
  }

  public AddressExtended streetNumber(String streetNumber) {
    this.streetNumber = streetNumber;
    return this;
  }

   /**
   * residenceCivic
   * @return streetNumber
  **/
  @ApiModelProperty(value = "residenceCivic")
  public String getStreetNumber() {
    return streetNumber;
  }

  public void setStreetNumber(String streetNumber) {
    this.streetNumber = streetNumber;
  }

  public AddressExtended postalCode(String postalCode) {
    this.postalCode = postalCode;
    return this;
  }

   /**
   * residencePostalCode
   * @return postalCode
  **/
  @ApiModelProperty(value = "residencePostalCode")
  public String getPostalCode() {
    return postalCode;
  }

  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }

  public AddressExtended municipality(String municipality) {
    this.municipality = municipality;
    return this;
  }

   /**
   * part of municipality
   * @return municipality
  **/
  @ApiModelProperty(value = "part of municipality")
  public String getMunicipality() {
    return municipality;
  }

  public void setMunicipality(String municipality) {
    this.municipality = municipality;
  }

  public AddressExtended others(String others) {
    this.others = others;
    return this;
  }

   /**
   * other indications
   * @return others
  **/
  @ApiModelProperty(value = "other indications")
  public String getOthers() {
    return others;
  }

  public void setOthers(String others) {
    this.others = others;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddressExtended addressExtended = (AddressExtended) o;
    return Objects.equals(this.city, addressExtended.city) &&
        Objects.equals(this.province, addressExtended.province) &&
        Objects.equals(this.nation, addressExtended.nation) &&
        Objects.equals(this.street, addressExtended.street) &&
        Objects.equals(this.streetNumber, addressExtended.streetNumber) &&
        Objects.equals(this.postalCode, addressExtended.postalCode) &&
        Objects.equals(this.municipality, addressExtended.municipality) &&
        Objects.equals(this.others, addressExtended.others);
  }

  @Override
  public int hashCode() {
    return Objects.hash(city, province, nation, street, streetNumber, postalCode, municipality, others);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddressExtended {\n");
    
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    province: ").append(toIndentedString(province)).append("\n");
    sb.append("    nation: ").append(toIndentedString(nation)).append("\n");
    sb.append("    street: ").append(toIndentedString(street)).append("\n");
    sb.append("    streetNumber: ").append(toIndentedString(streetNumber)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    municipality: ").append(toIndentedString(municipality)).append("\n");
    sb.append("    others: ").append(toIndentedString(others)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

