/*
 * Customer Reliability
 *  <b>Customer Reliability</b>  
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Address;
import io.swagger.client.model.CompanyBasicData;
import io.swagger.client.model.CustomerData;

/**
 * BeneficialOwner
 */

public class BeneficialOwner {
  @JsonProperty("companyInfo")
  private CompanyBasicData companyInfo = null;

  @JsonProperty("anagraphicalData")
  private CustomerData anagraphicalData = null;

  @JsonProperty("address")
  private Address address = null;

  @JsonProperty("crifNumber")
  private String crifNumber = null;

  @JsonProperty("roleCode")
  private String roleCode = null;

  @JsonProperty("roleDescription")
  private String roleDescription = null;

  @JsonProperty("cab")
  private String cab = null;

  @JsonProperty("cciaaCode")
  private String cciaaCode = null;

  @JsonProperty("reaCode")
  private String reaCode = null;

  @JsonProperty("legalNature")
  private String legalNature = null;

  @JsonProperty("companyParticipation")
  private String companyParticipation = null;

  @JsonProperty("flagPrejudicialDeeds")
  private Boolean flagPrejudicialDeeds = null;

  @JsonProperty("flagProtests")
  private Boolean flagProtests = null;

  public BeneficialOwner companyInfo(CompanyBasicData companyInfo) {
    this.companyInfo = companyInfo;
    return this;
  }

   /**
   * Get companyInfo
   * @return companyInfo
  **/
  @ApiModelProperty(value = "")
  public CompanyBasicData getCompanyInfo() {
    return companyInfo;
  }

  public void setCompanyInfo(CompanyBasicData companyInfo) {
    this.companyInfo = companyInfo;
  }

  public BeneficialOwner anagraphicalData(CustomerData anagraphicalData) {
    this.anagraphicalData = anagraphicalData;
    return this;
  }

   /**
   * Get anagraphicalData
   * @return anagraphicalData
  **/
  @ApiModelProperty(value = "")
  public CustomerData getAnagraphicalData() {
    return anagraphicalData;
  }

  public void setAnagraphicalData(CustomerData anagraphicalData) {
    this.anagraphicalData = anagraphicalData;
  }

  public BeneficialOwner address(Address address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @ApiModelProperty(value = "")
  public Address getAddress() {
    return address;
  }

  public void setAddress(Address address) {
    this.address = address;
  }

  public BeneficialOwner crifNumber(String crifNumber) {
    this.crifNumber = crifNumber;
    return this;
  }

   /**
   * crif number
   * @return crifNumber
  **/
  @ApiModelProperty(example = "12345", value = "crif number")
  public String getCrifNumber() {
    return crifNumber;
  }

  public void setCrifNumber(String crifNumber) {
    this.crifNumber = crifNumber;
  }

  public BeneficialOwner roleCode(String roleCode) {
    this.roleCode = roleCode;
    return this;
  }

   /**
   * role code of beneficial owner
   * @return roleCode
  **/
  @ApiModelProperty(value = "role code of beneficial owner")
  public String getRoleCode() {
    return roleCode;
  }

  public void setRoleCode(String roleCode) {
    this.roleCode = roleCode;
  }

  public BeneficialOwner roleDescription(String roleDescription) {
    this.roleDescription = roleDescription;
    return this;
  }

   /**
   * role description of beneficial owner
   * @return roleDescription
  **/
  @ApiModelProperty(value = "role description of beneficial owner")
  public String getRoleDescription() {
    return roleDescription;
  }

  public void setRoleDescription(String roleDescription) {
    this.roleDescription = roleDescription;
  }

  public BeneficialOwner cab(String cab) {
    this.cab = cab;
    return this;
  }

   /**
   * role description of beneficial owner
   * @return cab
  **/
  @ApiModelProperty(value = "role description of beneficial owner")
  public String getCab() {
    return cab;
  }

  public void setCab(String cab) {
    this.cab = cab;
  }

  public BeneficialOwner cciaaCode(String cciaaCode) {
    this.cciaaCode = cciaaCode;
    return this;
  }

   /**
   * cciaa code beneficial owner
   * @return cciaaCode
  **/
  @ApiModelProperty(value = "cciaa code beneficial owner")
  public String getCciaaCode() {
    return cciaaCode;
  }

  public void setCciaaCode(String cciaaCode) {
    this.cciaaCode = cciaaCode;
  }

  public BeneficialOwner reaCode(String reaCode) {
    this.reaCode = reaCode;
    return this;
  }

   /**
   * rea code beneficial owner
   * @return reaCode
  **/
  @ApiModelProperty(value = "rea code beneficial owner")
  public String getReaCode() {
    return reaCode;
  }

  public void setReaCode(String reaCode) {
    this.reaCode = reaCode;
  }

  public BeneficialOwner legalNature(String legalNature) {
    this.legalNature = legalNature;
    return this;
  }

   /**
   * legal nature of beneficial owner
   * @return legalNature
  **/
  @ApiModelProperty(value = "legal nature of beneficial owner")
  public String getLegalNature() {
    return legalNature;
  }

  public void setLegalNature(String legalNature) {
    this.legalNature = legalNature;
  }

  public BeneficialOwner companyParticipation(String companyParticipation) {
    this.companyParticipation = companyParticipation;
    return this;
  }

   /**
   * company participation of beneficial owner
   * @return companyParticipation
  **/
  @ApiModelProperty(value = "company participation of beneficial owner")
  public String getCompanyParticipation() {
    return companyParticipation;
  }

  public void setCompanyParticipation(String companyParticipation) {
    this.companyParticipation = companyParticipation;
  }

  public BeneficialOwner flagPrejudicialDeeds(Boolean flagPrejudicialDeeds) {
    this.flagPrejudicialDeeds = flagPrejudicialDeeds;
    return this;
  }

   /**
   * flag that indicate presence of Prejudicial Deeds
   * @return flagPrejudicialDeeds
  **/
  @ApiModelProperty(example = "false", value = "flag that indicate presence of Prejudicial Deeds")
  public Boolean isFlagPrejudicialDeeds() {
    return flagPrejudicialDeeds;
  }

  public void setFlagPrejudicialDeeds(Boolean flagPrejudicialDeeds) {
    this.flagPrejudicialDeeds = flagPrejudicialDeeds;
  }

  public BeneficialOwner flagProtests(Boolean flagProtests) {
    this.flagProtests = flagProtests;
    return this;
  }

   /**
   * flag that indicate presence of protests
   * @return flagProtests
  **/
  @ApiModelProperty(example = "false", value = "flag that indicate presence of protests")
  public Boolean isFlagProtests() {
    return flagProtests;
  }

  public void setFlagProtests(Boolean flagProtests) {
    this.flagProtests = flagProtests;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BeneficialOwner beneficialOwner = (BeneficialOwner) o;
    return Objects.equals(this.companyInfo, beneficialOwner.companyInfo) &&
        Objects.equals(this.anagraphicalData, beneficialOwner.anagraphicalData) &&
        Objects.equals(this.address, beneficialOwner.address) &&
        Objects.equals(this.crifNumber, beneficialOwner.crifNumber) &&
        Objects.equals(this.roleCode, beneficialOwner.roleCode) &&
        Objects.equals(this.roleDescription, beneficialOwner.roleDescription) &&
        Objects.equals(this.cab, beneficialOwner.cab) &&
        Objects.equals(this.cciaaCode, beneficialOwner.cciaaCode) &&
        Objects.equals(this.reaCode, beneficialOwner.reaCode) &&
        Objects.equals(this.legalNature, beneficialOwner.legalNature) &&
        Objects.equals(this.companyParticipation, beneficialOwner.companyParticipation) &&
        Objects.equals(this.flagPrejudicialDeeds, beneficialOwner.flagPrejudicialDeeds) &&
        Objects.equals(this.flagProtests, beneficialOwner.flagProtests);
  }

  @Override
  public int hashCode() {
    return Objects.hash(companyInfo, anagraphicalData, address, crifNumber, roleCode, roleDescription, cab, cciaaCode, reaCode, legalNature, companyParticipation, flagPrejudicialDeeds, flagProtests);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BeneficialOwner {\n");
    
    sb.append("    companyInfo: ").append(toIndentedString(companyInfo)).append("\n");
    sb.append("    anagraphicalData: ").append(toIndentedString(anagraphicalData)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    crifNumber: ").append(toIndentedString(crifNumber)).append("\n");
    sb.append("    roleCode: ").append(toIndentedString(roleCode)).append("\n");
    sb.append("    roleDescription: ").append(toIndentedString(roleDescription)).append("\n");
    sb.append("    cab: ").append(toIndentedString(cab)).append("\n");
    sb.append("    cciaaCode: ").append(toIndentedString(cciaaCode)).append("\n");
    sb.append("    reaCode: ").append(toIndentedString(reaCode)).append("\n");
    sb.append("    legalNature: ").append(toIndentedString(legalNature)).append("\n");
    sb.append("    companyParticipation: ").append(toIndentedString(companyParticipation)).append("\n");
    sb.append("    flagPrejudicialDeeds: ").append(toIndentedString(flagPrejudicialDeeds)).append("\n");
    sb.append("    flagProtests: ").append(toIndentedString(flagProtests)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

