/*
 * Customer Reliability
 *  <b>Customer Reliability</b>  
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * CompanyDetails
 */
@ApiModel(description = "CompanyDetails")

public class CompanyDetails {
  @JsonProperty("mtCompany")
  private String mtCompany = null;

  @JsonProperty("mtCompanyGroup")
  private String mtCompanyGroup = null;

  @JsonProperty("mtPartner")
  private String mtPartner = null;

  public CompanyDetails mtCompany(String mtCompany) {
    this.mtCompany = mtCompany;
    return this;
  }

   /**
   * mtCompany
   * @return mtCompany
  **/
  @ApiModelProperty(example = "NEXI", value = "mtCompany")
  public String getMtCompany() {
    return mtCompany;
  }

  public void setMtCompany(String mtCompany) {
    this.mtCompany = mtCompany;
  }

  public CompanyDetails mtCompanyGroup(String mtCompanyGroup) {
    this.mtCompanyGroup = mtCompanyGroup;
    return this;
  }

   /**
   * mtCompanyGroup
   * @return mtCompanyGroup
  **/
  @ApiModelProperty(example = "NEXI", value = "mtCompanyGroup")
  public String getMtCompanyGroup() {
    return mtCompanyGroup;
  }

  public void setMtCompanyGroup(String mtCompanyGroup) {
    this.mtCompanyGroup = mtCompanyGroup;
  }

  public CompanyDetails mtPartner(String mtPartner) {
    this.mtPartner = mtPartner;
    return this;
  }

   /**
   * mtPartner
   * @return mtPartner
  **/
  @ApiModelProperty(example = "NEXI", value = "mtPartner")
  public String getMtPartner() {
    return mtPartner;
  }

  public void setMtPartner(String mtPartner) {
    this.mtPartner = mtPartner;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CompanyDetails companyDetails = (CompanyDetails) o;
    return Objects.equals(this.mtCompany, companyDetails.mtCompany) &&
        Objects.equals(this.mtCompanyGroup, companyDetails.mtCompanyGroup) &&
        Objects.equals(this.mtPartner, companyDetails.mtPartner);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mtCompany, mtCompanyGroup, mtPartner);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CompanyDetails {\n");
    
    sb.append("    mtCompany: ").append(toIndentedString(mtCompany)).append("\n");
    sb.append("    mtCompanyGroup: ").append(toIndentedString(mtCompanyGroup)).append("\n");
    sb.append("    mtPartner: ").append(toIndentedString(mtPartner)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

