/*
 * Customer Reliability
 *  <b>Customer Reliability</b>  
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Address;
import io.swagger.client.model.Amount;
import io.swagger.client.model.Ateco07Classification;
import io.swagger.client.model.Balance;
import io.swagger.client.model.RiskIndicator;
import java.util.ArrayList;
import java.util.List;

/**
 * CompanyDetailsData
 */

public class CompanyDetailsData {
  @JsonProperty("cribisStatus")
  private String cribisStatus = null;

  @JsonProperty("atecoCode")
  private String atecoCode = null;

  @JsonProperty("legalForm")
  private String legalForm = null;

  @JsonProperty("legalFormDescription")
  private String legalFormDescription = null;

  @JsonProperty("startupYear")
  private String startupYear = null;

  @JsonProperty("annualRevenue")
  private String annualRevenue = null;

  @JsonProperty("annualRevenueYear")
  private String annualRevenueYear = null;

  @JsonProperty("annualRevenueProvenance")
  private String annualRevenueProvenance = null;

  @JsonProperty("profitValue")
  private String profitValue = null;

  @JsonProperty("raeCode")
  private String raeCode = null;

  @JsonProperty("raeDescription")
  private String raeDescription = null;

  @JsonProperty("saeCode")
  private String saeCode = null;

  @JsonProperty("saeDescription")
  private String saeDescription = null;

  @JsonProperty("flagPrejudicialDeeds")
  private Boolean flagPrejudicialDeeds = null;

  @JsonProperty("flagProtests")
  private Boolean flagProtests = null;

  @JsonProperty("flagBankruptcyProceedings")
  private Boolean flagBankruptcyProceedings = null;

  @JsonProperty("flagAssociates")
  private Boolean flagAssociates = null;

  @JsonProperty("activityStatus")
  private String activityStatus = null;

  @JsonProperty("status")
  private String status = null;

  @JsonProperty("flagRegistered")
  private Boolean flagRegistered = null;

  @JsonProperty("ateco07Classifications")
  private List<Ateco07Classification> ateco07Classifications = null;

  @JsonProperty("flagExistBankruptcyProceedings.")
  private Boolean flagExistBankruptcyProceedings_ = null;

  @JsonProperty("flagExistPrejudicialDeeds")
  private Boolean flagExistPrejudicialDeeds = null;

  @JsonProperty("flagExistVerifiedProtests")
  private Boolean flagExistVerifiedProtests = null;

  @JsonProperty("flagExistHomonimousProtests")
  private Boolean flagExistHomonimousProtests = null;

  @JsonProperty("otherRiskIndicators")
  private List<RiskIndicator> otherRiskIndicators = null;

  @JsonProperty("flagCorporateStructure")
  private Boolean flagCorporateStructure = null;

  @JsonProperty("flagExistNews")
  private Boolean flagExistNews = null;

  @JsonProperty("balance")
  private Balance balance = null;

  @JsonProperty("flagCommercialPayments")
  private Boolean flagCommercialPayments = null;

  @JsonProperty("bankCreditSuggested")
  private String bankCreditSuggested = null;

  @JsonProperty("failure")
  private String failure = null;

  @JsonProperty("delinquency")
  private String delinquency = null;

  @JsonProperty("paydex")
  private String paydex = null;

  @JsonProperty("flagExtraordinaryRedundancyFund")
  private Boolean flagExtraordinaryRedundancyFund = null;

  @JsonProperty("flagGroupsBelonging")
  private Boolean flagGroupsBelonging = null;

  @JsonProperty("shareCapital")
  private Amount shareCapital = null;

  @JsonProperty("address")
  private Address address = null;

  @JsonProperty("companyType")
  private String companyType = null;

  public CompanyDetailsData cribisStatus(String cribisStatus) {
    this.cribisStatus = cribisStatus;
    return this;
  }

   /**
   * cribis company status
   * @return cribisStatus
  **/
  @ApiModelProperty(value = "cribis company status")
  public String getCribisStatus() {
    return cribisStatus;
  }

  public void setCribisStatus(String cribisStatus) {
    this.cribisStatus = cribisStatus;
  }

  public CompanyDetailsData atecoCode(String atecoCode) {
    this.atecoCode = atecoCode;
    return this;
  }

   /**
   * ateco code company
   * @return atecoCode
  **/
  @ApiModelProperty(value = "ateco code company")
  public String getAtecoCode() {
    return atecoCode;
  }

  public void setAtecoCode(String atecoCode) {
    this.atecoCode = atecoCode;
  }

  public CompanyDetailsData legalForm(String legalForm) {
    this.legalForm = legalForm;
    return this;
  }

   /**
   * company legal Form
   * @return legalForm
  **/
  @ApiModelProperty(value = "company legal Form")
  public String getLegalForm() {
    return legalForm;
  }

  public void setLegalForm(String legalForm) {
    this.legalForm = legalForm;
  }

  public CompanyDetailsData legalFormDescription(String legalFormDescription) {
    this.legalFormDescription = legalFormDescription;
    return this;
  }

   /**
   * company legal Form
   * @return legalFormDescription
  **/
  @ApiModelProperty(value = "company legal Form")
  public String getLegalFormDescription() {
    return legalFormDescription;
  }

  public void setLegalFormDescription(String legalFormDescription) {
    this.legalFormDescription = legalFormDescription;
  }

  public CompanyDetailsData startupYear(String startupYear) {
    this.startupYear = startupYear;
    return this;
  }

   /**
   * company startup Year
   * @return startupYear
  **/
  @ApiModelProperty(example = "2020", value = "company startup Year")
  public String getStartupYear() {
    return startupYear;
  }

  public void setStartupYear(String startupYear) {
    this.startupYear = startupYear;
  }

  public CompanyDetailsData annualRevenue(String annualRevenue) {
    this.annualRevenue = annualRevenue;
    return this;
  }

   /**
   * company annual revenue
   * @return annualRevenue
  **/
  @ApiModelProperty(value = "company annual revenue")
  public String getAnnualRevenue() {
    return annualRevenue;
  }

  public void setAnnualRevenue(String annualRevenue) {
    this.annualRevenue = annualRevenue;
  }

  public CompanyDetailsData annualRevenueYear(String annualRevenueYear) {
    this.annualRevenueYear = annualRevenueYear;
    return this;
  }

   /**
   * company annual revenue year
   * @return annualRevenueYear
  **/
  @ApiModelProperty(example = "2020", value = "company annual revenue year")
  public String getAnnualRevenueYear() {
    return annualRevenueYear;
  }

  public void setAnnualRevenueYear(String annualRevenueYear) {
    this.annualRevenueYear = annualRevenueYear;
  }

  public CompanyDetailsData annualRevenueProvenance(String annualRevenueProvenance) {
    this.annualRevenueProvenance = annualRevenueProvenance;
    return this;
  }

   /**
   * company annual revenue provenance
   * @return annualRevenueProvenance
  **/
  @ApiModelProperty(value = "company annual revenue provenance")
  public String getAnnualRevenueProvenance() {
    return annualRevenueProvenance;
  }

  public void setAnnualRevenueProvenance(String annualRevenueProvenance) {
    this.annualRevenueProvenance = annualRevenueProvenance;
  }

  public CompanyDetailsData profitValue(String profitValue) {
    this.profitValue = profitValue;
    return this;
  }

   /**
   * company profit value
   * @return profitValue
  **/
  @ApiModelProperty(value = "company profit value")
  public String getProfitValue() {
    return profitValue;
  }

  public void setProfitValue(String profitValue) {
    this.profitValue = profitValue;
  }

  public CompanyDetailsData raeCode(String raeCode) {
    this.raeCode = raeCode;
    return this;
  }

   /**
   * company rae code
   * @return raeCode
  **/
  @ApiModelProperty(value = "company rae code")
  public String getRaeCode() {
    return raeCode;
  }

  public void setRaeCode(String raeCode) {
    this.raeCode = raeCode;
  }

  public CompanyDetailsData raeDescription(String raeDescription) {
    this.raeDescription = raeDescription;
    return this;
  }

   /**
   * company rae description
   * @return raeDescription
  **/
  @ApiModelProperty(value = "company rae description")
  public String getRaeDescription() {
    return raeDescription;
  }

  public void setRaeDescription(String raeDescription) {
    this.raeDescription = raeDescription;
  }

  public CompanyDetailsData saeCode(String saeCode) {
    this.saeCode = saeCode;
    return this;
  }

   /**
   * company sae code
   * @return saeCode
  **/
  @ApiModelProperty(value = "company sae code")
  public String getSaeCode() {
    return saeCode;
  }

  public void setSaeCode(String saeCode) {
    this.saeCode = saeCode;
  }

  public CompanyDetailsData saeDescription(String saeDescription) {
    this.saeDescription = saeDescription;
    return this;
  }

   /**
   * company sae description
   * @return saeDescription
  **/
  @ApiModelProperty(value = "company sae description")
  public String getSaeDescription() {
    return saeDescription;
  }

  public void setSaeDescription(String saeDescription) {
    this.saeDescription = saeDescription;
  }

  public CompanyDetailsData flagPrejudicialDeeds(Boolean flagPrejudicialDeeds) {
    this.flagPrejudicialDeeds = flagPrejudicialDeeds;
    return this;
  }

   /**
   * flag that indicate presence of Prejudicial Deeds
   * @return flagPrejudicialDeeds
  **/
  @ApiModelProperty(example = "false", value = "flag that indicate presence of Prejudicial Deeds")
  public Boolean isFlagPrejudicialDeeds() {
    return flagPrejudicialDeeds;
  }

  public void setFlagPrejudicialDeeds(Boolean flagPrejudicialDeeds) {
    this.flagPrejudicialDeeds = flagPrejudicialDeeds;
  }

  public CompanyDetailsData flagProtests(Boolean flagProtests) {
    this.flagProtests = flagProtests;
    return this;
  }

   /**
   * flag that indicate presence of protests
   * @return flagProtests
  **/
  @ApiModelProperty(example = "false", value = "flag that indicate presence of protests")
  public Boolean isFlagProtests() {
    return flagProtests;
  }

  public void setFlagProtests(Boolean flagProtests) {
    this.flagProtests = flagProtests;
  }

  public CompanyDetailsData flagBankruptcyProceedings(Boolean flagBankruptcyProceedings) {
    this.flagBankruptcyProceedings = flagBankruptcyProceedings;
    return this;
  }

   /**
   * flag that indicate presence of bankruptcy proceedings
   * @return flagBankruptcyProceedings
  **/
  @ApiModelProperty(example = "false", value = "flag that indicate presence of bankruptcy proceedings")
  public Boolean isFlagBankruptcyProceedings() {
    return flagBankruptcyProceedings;
  }

  public void setFlagBankruptcyProceedings(Boolean flagBankruptcyProceedings) {
    this.flagBankruptcyProceedings = flagBankruptcyProceedings;
  }

  public CompanyDetailsData flagAssociates(Boolean flagAssociates) {
    this.flagAssociates = flagAssociates;
    return this;
  }

   /**
   * flag that indicate presence of Associates
   * @return flagAssociates
  **/
  @ApiModelProperty(example = "false", value = "flag that indicate presence of Associates")
  public Boolean isFlagAssociates() {
    return flagAssociates;
  }

  public void setFlagAssociates(Boolean flagAssociates) {
    this.flagAssociates = flagAssociates;
  }

  public CompanyDetailsData activityStatus(String activityStatus) {
    this.activityStatus = activityStatus;
    return this;
  }

   /**
   * company activity status
   * @return activityStatus
  **/
  @ApiModelProperty(value = "company activity status")
  public String getActivityStatus() {
    return activityStatus;
  }

  public void setActivityStatus(String activityStatus) {
    this.activityStatus = activityStatus;
  }

  public CompanyDetailsData status(String status) {
    this.status = status;
    return this;
  }

   /**
   * company status
   * @return status
  **/
  @ApiModelProperty(value = "company status")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public CompanyDetailsData flagRegistered(Boolean flagRegistered) {
    this.flagRegistered = flagRegistered;
    return this;
  }

   /**
   * flag that indicate if company is registered
   * @return flagRegistered
  **/
  @ApiModelProperty(example = "false", value = "flag that indicate if company is registered")
  public Boolean isFlagRegistered() {
    return flagRegistered;
  }

  public void setFlagRegistered(Boolean flagRegistered) {
    this.flagRegistered = flagRegistered;
  }

  public CompanyDetailsData ateco07Classifications(List<Ateco07Classification> ateco07Classifications) {
    this.ateco07Classifications = ateco07Classifications;
    return this;
  }

  public CompanyDetailsData addAteco07ClassificationsItem(Ateco07Classification ateco07ClassificationsItem) {
    if (this.ateco07Classifications == null) {
      this.ateco07Classifications = new ArrayList<>();
    }
    this.ateco07Classifications.add(ateco07ClassificationsItem);
    return this;
  }

   /**
   * Get ateco07Classifications
   * @return ateco07Classifications
  **/
  @ApiModelProperty(value = "")
  public List<Ateco07Classification> getAteco07Classifications() {
    return ateco07Classifications;
  }

  public void setAteco07Classifications(List<Ateco07Classification> ateco07Classifications) {
    this.ateco07Classifications = ateco07Classifications;
  }

  public CompanyDetailsData flagExistBankruptcyProceedings_(Boolean flagExistBankruptcyProceedings_) {
    this.flagExistBankruptcyProceedings_ = flagExistBankruptcyProceedings_;
    return this;
  }

   /**
   * flag that indicate extisting of bankruptcy proceedings
   * @return flagExistBankruptcyProceedings_
  **/
  @ApiModelProperty(example = "false", value = "flag that indicate extisting of bankruptcy proceedings")
  public Boolean isFlagExistBankruptcyProceedings_() {
    return flagExistBankruptcyProceedings_;
  }

  public void setFlagExistBankruptcyProceedings_(Boolean flagExistBankruptcyProceedings_) {
    this.flagExistBankruptcyProceedings_ = flagExistBankruptcyProceedings_;
  }

  public CompanyDetailsData flagExistPrejudicialDeeds(Boolean flagExistPrejudicialDeeds) {
    this.flagExistPrejudicialDeeds = flagExistPrejudicialDeeds;
    return this;
  }

   /**
   * flag that indicate presence of Prejudicial Deeds
   * @return flagExistPrejudicialDeeds
  **/
  @ApiModelProperty(example = "false", value = "flag that indicate presence of Prejudicial Deeds")
  public Boolean isFlagExistPrejudicialDeeds() {
    return flagExistPrejudicialDeeds;
  }

  public void setFlagExistPrejudicialDeeds(Boolean flagExistPrejudicialDeeds) {
    this.flagExistPrejudicialDeeds = flagExistPrejudicialDeeds;
  }

  public CompanyDetailsData flagExistVerifiedProtests(Boolean flagExistVerifiedProtests) {
    this.flagExistVerifiedProtests = flagExistVerifiedProtests;
    return this;
  }

   /**
   * flag that indicate presence of VerifiedProtests
   * @return flagExistVerifiedProtests
  **/
  @ApiModelProperty(example = "false", value = "flag that indicate presence of VerifiedProtests")
  public Boolean isFlagExistVerifiedProtests() {
    return flagExistVerifiedProtests;
  }

  public void setFlagExistVerifiedProtests(Boolean flagExistVerifiedProtests) {
    this.flagExistVerifiedProtests = flagExistVerifiedProtests;
  }

  public CompanyDetailsData flagExistHomonimousProtests(Boolean flagExistHomonimousProtests) {
    this.flagExistHomonimousProtests = flagExistHomonimousProtests;
    return this;
  }

   /**
   * flag that indicate presence of Homonimous Protests
   * @return flagExistHomonimousProtests
  **/
  @ApiModelProperty(example = "false", value = "flag that indicate presence of Homonimous Protests")
  public Boolean isFlagExistHomonimousProtests() {
    return flagExistHomonimousProtests;
  }

  public void setFlagExistHomonimousProtests(Boolean flagExistHomonimousProtests) {
    this.flagExistHomonimousProtests = flagExistHomonimousProtests;
  }

  public CompanyDetailsData otherRiskIndicators(List<RiskIndicator> otherRiskIndicators) {
    this.otherRiskIndicators = otherRiskIndicators;
    return this;
  }

  public CompanyDetailsData addOtherRiskIndicatorsItem(RiskIndicator otherRiskIndicatorsItem) {
    if (this.otherRiskIndicators == null) {
      this.otherRiskIndicators = new ArrayList<>();
    }
    this.otherRiskIndicators.add(otherRiskIndicatorsItem);
    return this;
  }

   /**
   * Get otherRiskIndicators
   * @return otherRiskIndicators
  **/
  @ApiModelProperty(value = "")
  public List<RiskIndicator> getOtherRiskIndicators() {
    return otherRiskIndicators;
  }

  public void setOtherRiskIndicators(List<RiskIndicator> otherRiskIndicators) {
    this.otherRiskIndicators = otherRiskIndicators;
  }

  public CompanyDetailsData flagCorporateStructure(Boolean flagCorporateStructure) {
    this.flagCorporateStructure = flagCorporateStructure;
    return this;
  }

   /**
   * flag corporate structure
   * @return flagCorporateStructure
  **/
  @ApiModelProperty(example = "false", value = "flag corporate structure")
  public Boolean isFlagCorporateStructure() {
    return flagCorporateStructure;
  }

  public void setFlagCorporateStructure(Boolean flagCorporateStructure) {
    this.flagCorporateStructure = flagCorporateStructure;
  }

  public CompanyDetailsData flagExistNews(Boolean flagExistNews) {
    this.flagExistNews = flagExistNews;
    return this;
  }

   /**
   * flag exist news
   * @return flagExistNews
  **/
  @ApiModelProperty(example = "false", value = "flag exist news")
  public Boolean isFlagExistNews() {
    return flagExistNews;
  }

  public void setFlagExistNews(Boolean flagExistNews) {
    this.flagExistNews = flagExistNews;
  }

  public CompanyDetailsData balance(Balance balance) {
    this.balance = balance;
    return this;
  }

   /**
   * Get balance
   * @return balance
  **/
  @ApiModelProperty(value = "")
  public Balance getBalance() {
    return balance;
  }

  public void setBalance(Balance balance) {
    this.balance = balance;
  }

  public CompanyDetailsData flagCommercialPayments(Boolean flagCommercialPayments) {
    this.flagCommercialPayments = flagCommercialPayments;
    return this;
  }

   /**
   * flag commercial payments
   * @return flagCommercialPayments
  **/
  @ApiModelProperty(example = "false", value = "flag commercial payments")
  public Boolean isFlagCommercialPayments() {
    return flagCommercialPayments;
  }

  public void setFlagCommercialPayments(Boolean flagCommercialPayments) {
    this.flagCommercialPayments = flagCommercialPayments;
  }

  public CompanyDetailsData bankCreditSuggested(String bankCreditSuggested) {
    this.bankCreditSuggested = bankCreditSuggested;
    return this;
  }

   /**
   * bank credit suggested
   * @return bankCreditSuggested
  **/
  @ApiModelProperty(value = "bank credit suggested")
  public String getBankCreditSuggested() {
    return bankCreditSuggested;
  }

  public void setBankCreditSuggested(String bankCreditSuggested) {
    this.bankCreditSuggested = bankCreditSuggested;
  }

  public CompanyDetailsData failure(String failure) {
    this.failure = failure;
    return this;
  }

   /**
   * failure
   * @return failure
  **/
  @ApiModelProperty(value = "failure")
  public String getFailure() {
    return failure;
  }

  public void setFailure(String failure) {
    this.failure = failure;
  }

  public CompanyDetailsData delinquency(String delinquency) {
    this.delinquency = delinquency;
    return this;
  }

   /**
   * delinquency
   * @return delinquency
  **/
  @ApiModelProperty(value = "delinquency")
  public String getDelinquency() {
    return delinquency;
  }

  public void setDelinquency(String delinquency) {
    this.delinquency = delinquency;
  }

  public CompanyDetailsData paydex(String paydex) {
    this.paydex = paydex;
    return this;
  }

   /**
   * paydex
   * @return paydex
  **/
  @ApiModelProperty(value = "paydex")
  public String getPaydex() {
    return paydex;
  }

  public void setPaydex(String paydex) {
    this.paydex = paydex;
  }

  public CompanyDetailsData flagExtraordinaryRedundancyFund(Boolean flagExtraordinaryRedundancyFund) {
    this.flagExtraordinaryRedundancyFund = flagExtraordinaryRedundancyFund;
    return this;
  }

   /**
   * flag extraordinary redundancy fund
   * @return flagExtraordinaryRedundancyFund
  **/
  @ApiModelProperty(example = "false", value = "flag extraordinary redundancy fund")
  public Boolean isFlagExtraordinaryRedundancyFund() {
    return flagExtraordinaryRedundancyFund;
  }

  public void setFlagExtraordinaryRedundancyFund(Boolean flagExtraordinaryRedundancyFund) {
    this.flagExtraordinaryRedundancyFund = flagExtraordinaryRedundancyFund;
  }

  public CompanyDetailsData flagGroupsBelonging(Boolean flagGroupsBelonging) {
    this.flagGroupsBelonging = flagGroupsBelonging;
    return this;
  }

   /**
   * flag groups belonging
   * @return flagGroupsBelonging
  **/
  @ApiModelProperty(example = "false", value = "flag groups belonging")
  public Boolean isFlagGroupsBelonging() {
    return flagGroupsBelonging;
  }

  public void setFlagGroupsBelonging(Boolean flagGroupsBelonging) {
    this.flagGroupsBelonging = flagGroupsBelonging;
  }

  public CompanyDetailsData shareCapital(Amount shareCapital) {
    this.shareCapital = shareCapital;
    return this;
  }

   /**
   * share capital
   * @return shareCapital
  **/
  @ApiModelProperty(value = "share capital")
  public Amount getShareCapital() {
    return shareCapital;
  }

  public void setShareCapital(Amount shareCapital) {
    this.shareCapital = shareCapital;
  }

  public CompanyDetailsData address(Address address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @ApiModelProperty(value = "")
  public Address getAddress() {
    return address;
  }

  public void setAddress(Address address) {
    this.address = address;
  }

  public CompanyDetailsData companyType(String companyType) {
    this.companyType = companyType;
    return this;
  }

   /**
   * paydex
   * @return companyType
  **/
  @ApiModelProperty(example = "SC", value = "paydex")
  public String getCompanyType() {
    return companyType;
  }

  public void setCompanyType(String companyType) {
    this.companyType = companyType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CompanyDetailsData companyDetailsData = (CompanyDetailsData) o;
    return Objects.equals(this.cribisStatus, companyDetailsData.cribisStatus) &&
        Objects.equals(this.atecoCode, companyDetailsData.atecoCode) &&
        Objects.equals(this.legalForm, companyDetailsData.legalForm) &&
        Objects.equals(this.legalFormDescription, companyDetailsData.legalFormDescription) &&
        Objects.equals(this.startupYear, companyDetailsData.startupYear) &&
        Objects.equals(this.annualRevenue, companyDetailsData.annualRevenue) &&
        Objects.equals(this.annualRevenueYear, companyDetailsData.annualRevenueYear) &&
        Objects.equals(this.annualRevenueProvenance, companyDetailsData.annualRevenueProvenance) &&
        Objects.equals(this.profitValue, companyDetailsData.profitValue) &&
        Objects.equals(this.raeCode, companyDetailsData.raeCode) &&
        Objects.equals(this.raeDescription, companyDetailsData.raeDescription) &&
        Objects.equals(this.saeCode, companyDetailsData.saeCode) &&
        Objects.equals(this.saeDescription, companyDetailsData.saeDescription) &&
        Objects.equals(this.flagPrejudicialDeeds, companyDetailsData.flagPrejudicialDeeds) &&
        Objects.equals(this.flagProtests, companyDetailsData.flagProtests) &&
        Objects.equals(this.flagBankruptcyProceedings, companyDetailsData.flagBankruptcyProceedings) &&
        Objects.equals(this.flagAssociates, companyDetailsData.flagAssociates) &&
        Objects.equals(this.activityStatus, companyDetailsData.activityStatus) &&
        Objects.equals(this.status, companyDetailsData.status) &&
        Objects.equals(this.flagRegistered, companyDetailsData.flagRegistered) &&
        Objects.equals(this.ateco07Classifications, companyDetailsData.ateco07Classifications) &&
        Objects.equals(this.flagExistBankruptcyProceedings_, companyDetailsData.flagExistBankruptcyProceedings_) &&
        Objects.equals(this.flagExistPrejudicialDeeds, companyDetailsData.flagExistPrejudicialDeeds) &&
        Objects.equals(this.flagExistVerifiedProtests, companyDetailsData.flagExistVerifiedProtests) &&
        Objects.equals(this.flagExistHomonimousProtests, companyDetailsData.flagExistHomonimousProtests) &&
        Objects.equals(this.otherRiskIndicators, companyDetailsData.otherRiskIndicators) &&
        Objects.equals(this.flagCorporateStructure, companyDetailsData.flagCorporateStructure) &&
        Objects.equals(this.flagExistNews, companyDetailsData.flagExistNews) &&
        Objects.equals(this.balance, companyDetailsData.balance) &&
        Objects.equals(this.flagCommercialPayments, companyDetailsData.flagCommercialPayments) &&
        Objects.equals(this.bankCreditSuggested, companyDetailsData.bankCreditSuggested) &&
        Objects.equals(this.failure, companyDetailsData.failure) &&
        Objects.equals(this.delinquency, companyDetailsData.delinquency) &&
        Objects.equals(this.paydex, companyDetailsData.paydex) &&
        Objects.equals(this.flagExtraordinaryRedundancyFund, companyDetailsData.flagExtraordinaryRedundancyFund) &&
        Objects.equals(this.flagGroupsBelonging, companyDetailsData.flagGroupsBelonging) &&
        Objects.equals(this.shareCapital, companyDetailsData.shareCapital) &&
        Objects.equals(this.address, companyDetailsData.address) &&
        Objects.equals(this.companyType, companyDetailsData.companyType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cribisStatus, atecoCode, legalForm, legalFormDescription, startupYear, annualRevenue, annualRevenueYear, annualRevenueProvenance, profitValue, raeCode, raeDescription, saeCode, saeDescription, flagPrejudicialDeeds, flagProtests, flagBankruptcyProceedings, flagAssociates, activityStatus, status, flagRegistered, ateco07Classifications, flagExistBankruptcyProceedings_, flagExistPrejudicialDeeds, flagExistVerifiedProtests, flagExistHomonimousProtests, otherRiskIndicators, flagCorporateStructure, flagExistNews, balance, flagCommercialPayments, bankCreditSuggested, failure, delinquency, paydex, flagExtraordinaryRedundancyFund, flagGroupsBelonging, shareCapital, address, companyType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CompanyDetailsData {\n");
    
    sb.append("    cribisStatus: ").append(toIndentedString(cribisStatus)).append("\n");
    sb.append("    atecoCode: ").append(toIndentedString(atecoCode)).append("\n");
    sb.append("    legalForm: ").append(toIndentedString(legalForm)).append("\n");
    sb.append("    legalFormDescription: ").append(toIndentedString(legalFormDescription)).append("\n");
    sb.append("    startupYear: ").append(toIndentedString(startupYear)).append("\n");
    sb.append("    annualRevenue: ").append(toIndentedString(annualRevenue)).append("\n");
    sb.append("    annualRevenueYear: ").append(toIndentedString(annualRevenueYear)).append("\n");
    sb.append("    annualRevenueProvenance: ").append(toIndentedString(annualRevenueProvenance)).append("\n");
    sb.append("    profitValue: ").append(toIndentedString(profitValue)).append("\n");
    sb.append("    raeCode: ").append(toIndentedString(raeCode)).append("\n");
    sb.append("    raeDescription: ").append(toIndentedString(raeDescription)).append("\n");
    sb.append("    saeCode: ").append(toIndentedString(saeCode)).append("\n");
    sb.append("    saeDescription: ").append(toIndentedString(saeDescription)).append("\n");
    sb.append("    flagPrejudicialDeeds: ").append(toIndentedString(flagPrejudicialDeeds)).append("\n");
    sb.append("    flagProtests: ").append(toIndentedString(flagProtests)).append("\n");
    sb.append("    flagBankruptcyProceedings: ").append(toIndentedString(flagBankruptcyProceedings)).append("\n");
    sb.append("    flagAssociates: ").append(toIndentedString(flagAssociates)).append("\n");
    sb.append("    activityStatus: ").append(toIndentedString(activityStatus)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    flagRegistered: ").append(toIndentedString(flagRegistered)).append("\n");
    sb.append("    ateco07Classifications: ").append(toIndentedString(ateco07Classifications)).append("\n");
    sb.append("    flagExistBankruptcyProceedings_: ").append(toIndentedString(flagExistBankruptcyProceedings_)).append("\n");
    sb.append("    flagExistPrejudicialDeeds: ").append(toIndentedString(flagExistPrejudicialDeeds)).append("\n");
    sb.append("    flagExistVerifiedProtests: ").append(toIndentedString(flagExistVerifiedProtests)).append("\n");
    sb.append("    flagExistHomonimousProtests: ").append(toIndentedString(flagExistHomonimousProtests)).append("\n");
    sb.append("    otherRiskIndicators: ").append(toIndentedString(otherRiskIndicators)).append("\n");
    sb.append("    flagCorporateStructure: ").append(toIndentedString(flagCorporateStructure)).append("\n");
    sb.append("    flagExistNews: ").append(toIndentedString(flagExistNews)).append("\n");
    sb.append("    balance: ").append(toIndentedString(balance)).append("\n");
    sb.append("    flagCommercialPayments: ").append(toIndentedString(flagCommercialPayments)).append("\n");
    sb.append("    bankCreditSuggested: ").append(toIndentedString(bankCreditSuggested)).append("\n");
    sb.append("    failure: ").append(toIndentedString(failure)).append("\n");
    sb.append("    delinquency: ").append(toIndentedString(delinquency)).append("\n");
    sb.append("    paydex: ").append(toIndentedString(paydex)).append("\n");
    sb.append("    flagExtraordinaryRedundancyFund: ").append(toIndentedString(flagExtraordinaryRedundancyFund)).append("\n");
    sb.append("    flagGroupsBelonging: ").append(toIndentedString(flagGroupsBelonging)).append("\n");
    sb.append("    shareCapital: ").append(toIndentedString(shareCapital)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    companyType: ").append(toIndentedString(companyType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

