/*
 * Customer Reliability
 *  <b>Customer Reliability</b>  
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.CustomerIdentificationDocument;
import org.joda.time.LocalDate;

/**
 * CustomerDocumentSubscription
 */

public class CustomerDocumentSubscription {
  /**
   * documentType
   */
  public enum DocumentTypeEnum {
    _1("1"),
    
    _2("2"),
    
    _3("3"),
    
    _4("4");

    private String value;

    DocumentTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DocumentTypeEnum fromValue(String text) {
      for (DocumentTypeEnum b : DocumentTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("documentType")
  private DocumentTypeEnum documentType = null;

  @JsonProperty("documentNumber")
  private String documentNumber = null;

  @JsonProperty("issueLocation")
  private String issueLocation = null;

  @JsonProperty("issueProvince")
  private String issueProvince = null;

  @JsonProperty("issueNation")
  private String issueNation = null;

  @JsonProperty("issueDate")
  private LocalDate issueDate = null;

  @JsonProperty("expirationDate")
  private LocalDate expirationDate = null;

  @JsonProperty("extendedDocumentName")
  private String extendedDocumentName = null;

  @JsonProperty("otherDocumentType")
  private String otherDocumentType = null;

  @JsonProperty("releaseDate")
  private LocalDate releaseDate = null;

  @JsonProperty("documentIssuer")
  private String documentIssuer = null;

  @JsonProperty("issueNationUifCode")
  private String issueNationUifCode = null;

  @JsonProperty("issueNationIsoCode")
  private String issueNationIsoCode = null;

  public CustomerDocumentSubscription documentType(DocumentTypeEnum documentType) {
    this.documentType = documentType;
    return this;
  }

   /**
   * documentType
   * @return documentType
  **/
  @ApiModelProperty(value = "documentType")
  public DocumentTypeEnum getDocumentType() {
    return documentType;
  }

  public void setDocumentType(DocumentTypeEnum documentType) {
    this.documentType = documentType;
  }

  public CustomerDocumentSubscription documentNumber(String documentNumber) {
    this.documentNumber = documentNumber;
    return this;
  }

   /**
   * documentNumber
   * @return documentNumber
  **/
  @ApiModelProperty(value = "documentNumber")
  public String getDocumentNumber() {
    return documentNumber;
  }

  public void setDocumentNumber(String documentNumber) {
    this.documentNumber = documentNumber;
  }

  public CustomerDocumentSubscription issueLocation(String issueLocation) {
    this.issueLocation = issueLocation;
    return this;
  }

   /**
   * issueLocation
   * @return issueLocation
  **/
  @ApiModelProperty(value = "issueLocation")
  public String getIssueLocation() {
    return issueLocation;
  }

  public void setIssueLocation(String issueLocation) {
    this.issueLocation = issueLocation;
  }

  public CustomerDocumentSubscription issueProvince(String issueProvince) {
    this.issueProvince = issueProvince;
    return this;
  }

   /**
   * issueProvince
   * @return issueProvince
  **/
  @ApiModelProperty(value = "issueProvince")
  public String getIssueProvince() {
    return issueProvince;
  }

  public void setIssueProvince(String issueProvince) {
    this.issueProvince = issueProvince;
  }

  public CustomerDocumentSubscription issueNation(String issueNation) {
    this.issueNation = issueNation;
    return this;
  }

   /**
   * issueNation
   * @return issueNation
  **/
  @ApiModelProperty(value = "issueNation")
  public String getIssueNation() {
    return issueNation;
  }

  public void setIssueNation(String issueNation) {
    this.issueNation = issueNation;
  }

  public CustomerDocumentSubscription issueDate(LocalDate issueDate) {
    this.issueDate = issueDate;
    return this;
  }

   /**
   * issueDate
   * @return issueDate
  **/
  @ApiModelProperty(value = "issueDate")
  public LocalDate getIssueDate() {
    return issueDate;
  }

  public void setIssueDate(LocalDate issueDate) {
    this.issueDate = issueDate;
  }

  public CustomerDocumentSubscription expirationDate(LocalDate expirationDate) {
    this.expirationDate = expirationDate;
    return this;
  }

   /**
   * expirationDate
   * @return expirationDate
  **/
  @ApiModelProperty(value = "expirationDate")
  public LocalDate getExpirationDate() {
    return expirationDate;
  }

  public void setExpirationDate(LocalDate expirationDate) {
    this.expirationDate = expirationDate;
  }

  public CustomerDocumentSubscription extendedDocumentName(String extendedDocumentName) {
    this.extendedDocumentName = extendedDocumentName;
    return this;
  }

   /**
   * extended document name
   * @return extendedDocumentName
  **/
  @ApiModelProperty(example = "TESSERA POSTALE", value = "extended document name")
  public String getExtendedDocumentName() {
    return extendedDocumentName;
  }

  public void setExtendedDocumentName(String extendedDocumentName) {
    this.extendedDocumentName = extendedDocumentName;
  }

  public CustomerDocumentSubscription otherDocumentType(String otherDocumentType) {
    this.otherDocumentType = otherDocumentType;
    return this;
  }

   /**
   * documentType
   * @return otherDocumentType
  **/
  @ApiModelProperty(example = "05", value = "documentType")
  public String getOtherDocumentType() {
    return otherDocumentType;
  }

  public void setOtherDocumentType(String otherDocumentType) {
    this.otherDocumentType = otherDocumentType;
  }

  public CustomerDocumentSubscription releaseDate(LocalDate releaseDate) {
    this.releaseDate = releaseDate;
    return this;
  }

   /**
   * release date
   * @return releaseDate
  **/
  @ApiModelProperty(value = "release date")
  public LocalDate getReleaseDate() {
    return releaseDate;
  }

  public void setReleaseDate(LocalDate releaseDate) {
    this.releaseDate = releaseDate;
  }

  public CustomerDocumentSubscription documentIssuer(String documentIssuer) {
    this.documentIssuer = documentIssuer;
    return this;
  }

   /**
   * document issuer
   * @return documentIssuer
  **/
  @ApiModelProperty(example = "COMUNE", value = "document issuer")
  public String getDocumentIssuer() {
    return documentIssuer;
  }

  public void setDocumentIssuer(String documentIssuer) {
    this.documentIssuer = documentIssuer;
  }

  public CustomerDocumentSubscription issueNationUifCode(String issueNationUifCode) {
    this.issueNationUifCode = issueNationUifCode;
    return this;
  }

   /**
   * document issuer uic code
   * @return issueNationUifCode
  **/
  @ApiModelProperty(example = "086", value = "document issuer uic code")
  public String getIssueNationUifCode() {
    return issueNationUifCode;
  }

  public void setIssueNationUifCode(String issueNationUifCode) {
    this.issueNationUifCode = issueNationUifCode;
  }

  public CustomerDocumentSubscription issueNationIsoCode(String issueNationIsoCode) {
    this.issueNationIsoCode = issueNationIsoCode;
    return this;
  }

   /**
   * document issuer iso code
   * @return issueNationIsoCode
  **/
  @ApiModelProperty(example = "IT", value = "document issuer iso code")
  public String getIssueNationIsoCode() {
    return issueNationIsoCode;
  }

  public void setIssueNationIsoCode(String issueNationIsoCode) {
    this.issueNationIsoCode = issueNationIsoCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerDocumentSubscription customerDocumentSubscription = (CustomerDocumentSubscription) o;
    return Objects.equals(this.documentType, customerDocumentSubscription.documentType) &&
        Objects.equals(this.documentNumber, customerDocumentSubscription.documentNumber) &&
        Objects.equals(this.issueLocation, customerDocumentSubscription.issueLocation) &&
        Objects.equals(this.issueProvince, customerDocumentSubscription.issueProvince) &&
        Objects.equals(this.issueNation, customerDocumentSubscription.issueNation) &&
        Objects.equals(this.issueDate, customerDocumentSubscription.issueDate) &&
        Objects.equals(this.expirationDate, customerDocumentSubscription.expirationDate) &&
        Objects.equals(this.extendedDocumentName, customerDocumentSubscription.extendedDocumentName) &&
        Objects.equals(this.otherDocumentType, customerDocumentSubscription.otherDocumentType) &&
        Objects.equals(this.releaseDate, customerDocumentSubscription.releaseDate) &&
        Objects.equals(this.documentIssuer, customerDocumentSubscription.documentIssuer) &&
        Objects.equals(this.issueNationUifCode, customerDocumentSubscription.issueNationUifCode) &&
        Objects.equals(this.issueNationIsoCode, customerDocumentSubscription.issueNationIsoCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(documentType, documentNumber, issueLocation, issueProvince, issueNation, issueDate, expirationDate, extendedDocumentName, otherDocumentType, releaseDate, documentIssuer, issueNationUifCode, issueNationIsoCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerDocumentSubscription {\n");
    
    sb.append("    documentType: ").append(toIndentedString(documentType)).append("\n");
    sb.append("    documentNumber: ").append(toIndentedString(documentNumber)).append("\n");
    sb.append("    issueLocation: ").append(toIndentedString(issueLocation)).append("\n");
    sb.append("    issueProvince: ").append(toIndentedString(issueProvince)).append("\n");
    sb.append("    issueNation: ").append(toIndentedString(issueNation)).append("\n");
    sb.append("    issueDate: ").append(toIndentedString(issueDate)).append("\n");
    sb.append("    expirationDate: ").append(toIndentedString(expirationDate)).append("\n");
    sb.append("    extendedDocumentName: ").append(toIndentedString(extendedDocumentName)).append("\n");
    sb.append("    otherDocumentType: ").append(toIndentedString(otherDocumentType)).append("\n");
    sb.append("    releaseDate: ").append(toIndentedString(releaseDate)).append("\n");
    sb.append("    documentIssuer: ").append(toIndentedString(documentIssuer)).append("\n");
    sb.append("    issueNationUifCode: ").append(toIndentedString(issueNationUifCode)).append("\n");
    sb.append("    issueNationIsoCode: ").append(toIndentedString(issueNationIsoCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

