/*
 * Customer Reliability
 *  <b>Customer Reliability</b>  
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.CustomerData;
import org.joda.time.LocalDate;

/**
 * CustomerDataSubscription
 */

public class CustomerDataSubscription {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("surname")
  private String surname = null;

  @JsonProperty("fiscalCode")
  private String fiscalCode = null;

  @JsonProperty("sex")
  private String sex = null;

  @JsonProperty("birthDate")
  private LocalDate birthDate = null;

  @JsonProperty("birthCity")
  private String birthCity = null;

  @JsonProperty("birthProvince")
  private String birthProvince = null;

  @JsonProperty("birthNation")
  private String birthNation = null;

  @JsonProperty("citizenship")
  private String citizenship = null;

  @JsonProperty("birthNationUifCode")
  private String birthNationUifCode = null;

  @JsonProperty("birthNationIsoCode")
  private String birthNationIsoCode = null;

  public CustomerDataSubscription name(String name) {
    this.name = name;
    return this;
  }

   /**
   * name of the card owner
   * @return name
  **/
  @ApiModelProperty(example = "Mario", value = "name of the card owner")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CustomerDataSubscription surname(String surname) {
    this.surname = surname;
    return this;
  }

   /**
   * surname of the card owner
   * @return surname
  **/
  @ApiModelProperty(example = "Rossi", value = "surname of the card owner")
  public String getSurname() {
    return surname;
  }

  public void setSurname(String surname) {
    this.surname = surname;
  }

  public CustomerDataSubscription fiscalCode(String fiscalCode) {
    this.fiscalCode = fiscalCode;
    return this;
  }

   /**
   * fiscal code of the card owner
   * @return fiscalCode
  **/
  @ApiModelProperty(example = "RSSMRA81M18D121R", value = "fiscal code of the card owner")
  public String getFiscalCode() {
    return fiscalCode;
  }

  public void setFiscalCode(String fiscalCode) {
    this.fiscalCode = fiscalCode;
  }

  public CustomerDataSubscription sex(String sex) {
    this.sex = sex;
    return this;
  }

   /**
   * sex of card owner [F,M]
   * @return sex
  **/
  @ApiModelProperty(example = "M", value = "sex of card owner [F,M]")
  public String getSex() {
    return sex;
  }

  public void setSex(String sex) {
    this.sex = sex;
  }

  public CustomerDataSubscription birthDate(LocalDate birthDate) {
    this.birthDate = birthDate;
    return this;
  }

   /**
   * card owner&#39;s date of birth
   * @return birthDate
  **/
  @ApiModelProperty(example = "2000-10-02", value = "card owner's date of birth")
  public LocalDate getBirthDate() {
    return birthDate;
  }

  public void setBirthDate(LocalDate birthDate) {
    this.birthDate = birthDate;
  }

  public CustomerDataSubscription birthCity(String birthCity) {
    this.birthCity = birthCity;
    return this;
  }

   /**
   * card owner&#39;s city of birth
   * @return birthCity
  **/
  @ApiModelProperty(example = "Sesto San Giovanni", value = "card owner's city of birth")
  public String getBirthCity() {
    return birthCity;
  }

  public void setBirthCity(String birthCity) {
    this.birthCity = birthCity;
  }

  public CustomerDataSubscription birthProvince(String birthProvince) {
    this.birthProvince = birthProvince;
    return this;
  }

   /**
   * card owner&#39;s province of birth (only italian customers)
   * @return birthProvince
  **/
  @ApiModelProperty(example = "MI", value = "card owner's province of birth (only italian customers)")
  public String getBirthProvince() {
    return birthProvince;
  }

  public void setBirthProvince(String birthProvince) {
    this.birthProvince = birthProvince;
  }

  public CustomerDataSubscription birthNation(String birthNation) {
    this.birthNation = birthNation;
    return this;
  }

   /**
   * card owner&#39;s nation of birth
   * @return birthNation
  **/
  @ApiModelProperty(example = "Italy", value = "card owner's nation of birth")
  public String getBirthNation() {
    return birthNation;
  }

  public void setBirthNation(String birthNation) {
    this.birthNation = birthNation;
  }

  public CustomerDataSubscription citizenship(String citizenship) {
    this.citizenship = citizenship;
    return this;
  }

   /**
   * citizenship
   * @return citizenship
  **/
  @ApiModelProperty(value = "citizenship")
  public String getCitizenship() {
    return citizenship;
  }

  public void setCitizenship(String citizenship) {
    this.citizenship = citizenship;
  }

  public CustomerDataSubscription birthNationUifCode(String birthNationUifCode) {
    this.birthNationUifCode = birthNationUifCode;
    return this;
  }

   /**
   * uif code of nation
   * @return birthNationUifCode
  **/
  @ApiModelProperty(example = "086", value = "uif code of nation")
  public String getBirthNationUifCode() {
    return birthNationUifCode;
  }

  public void setBirthNationUifCode(String birthNationUifCode) {
    this.birthNationUifCode = birthNationUifCode;
  }

  public CustomerDataSubscription birthNationIsoCode(String birthNationIsoCode) {
    this.birthNationIsoCode = birthNationIsoCode;
    return this;
  }

   /**
   * iso code of nation
   * @return birthNationIsoCode
  **/
  @ApiModelProperty(example = "IT", value = "iso code of nation")
  public String getBirthNationIsoCode() {
    return birthNationIsoCode;
  }

  public void setBirthNationIsoCode(String birthNationIsoCode) {
    this.birthNationIsoCode = birthNationIsoCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerDataSubscription customerDataSubscription = (CustomerDataSubscription) o;
    return Objects.equals(this.name, customerDataSubscription.name) &&
        Objects.equals(this.surname, customerDataSubscription.surname) &&
        Objects.equals(this.fiscalCode, customerDataSubscription.fiscalCode) &&
        Objects.equals(this.sex, customerDataSubscription.sex) &&
        Objects.equals(this.birthDate, customerDataSubscription.birthDate) &&
        Objects.equals(this.birthCity, customerDataSubscription.birthCity) &&
        Objects.equals(this.birthProvince, customerDataSubscription.birthProvince) &&
        Objects.equals(this.birthNation, customerDataSubscription.birthNation) &&
        Objects.equals(this.citizenship, customerDataSubscription.citizenship) &&
        Objects.equals(this.birthNationUifCode, customerDataSubscription.birthNationUifCode) &&
        Objects.equals(this.birthNationIsoCode, customerDataSubscription.birthNationIsoCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, surname, fiscalCode, sex, birthDate, birthCity, birthProvince, birthNation, citizenship, birthNationUifCode, birthNationIsoCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerDataSubscription {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    surname: ").append(toIndentedString(surname)).append("\n");
    sb.append("    fiscalCode: ").append(toIndentedString(fiscalCode)).append("\n");
    sb.append("    sex: ").append(toIndentedString(sex)).append("\n");
    sb.append("    birthDate: ").append(toIndentedString(birthDate)).append("\n");
    sb.append("    birthCity: ").append(toIndentedString(birthCity)).append("\n");
    sb.append("    birthProvince: ").append(toIndentedString(birthProvince)).append("\n");
    sb.append("    birthNation: ").append(toIndentedString(birthNation)).append("\n");
    sb.append("    citizenship: ").append(toIndentedString(citizenship)).append("\n");
    sb.append("    birthNationUifCode: ").append(toIndentedString(birthNationUifCode)).append("\n");
    sb.append("    birthNationIsoCode: ").append(toIndentedString(birthNationIsoCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

