/*
 * Customer Reliability
 *  <b>Customer Reliability</b>  
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.LocalDate;

/**
 * CustomerIdentificationDocument
 */

public class CustomerIdentificationDocument {
  /**
   * documentType
   */
  public enum DocumentTypeEnum {
    _1("1"),
    
    _2("2"),
    
    _3("3"),
    
    _4("4");

    private String value;

    DocumentTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DocumentTypeEnum fromValue(String text) {
      for (DocumentTypeEnum b : DocumentTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("documentType")
  private DocumentTypeEnum documentType = null;

  @JsonProperty("documentNumber")
  private String documentNumber = null;

  @JsonProperty("issueLocation")
  private String issueLocation = null;

  @JsonProperty("issueProvince")
  private String issueProvince = null;

  @JsonProperty("issueNation")
  private String issueNation = null;

  @JsonProperty("issueDate")
  private LocalDate issueDate = null;

  @JsonProperty("expirationDate")
  private LocalDate expirationDate = null;

  public CustomerIdentificationDocument documentType(DocumentTypeEnum documentType) {
    this.documentType = documentType;
    return this;
  }

   /**
   * documentType
   * @return documentType
  **/
  @ApiModelProperty(value = "documentType")
  public DocumentTypeEnum getDocumentType() {
    return documentType;
  }

  public void setDocumentType(DocumentTypeEnum documentType) {
    this.documentType = documentType;
  }

  public CustomerIdentificationDocument documentNumber(String documentNumber) {
    this.documentNumber = documentNumber;
    return this;
  }

   /**
   * documentNumber
   * @return documentNumber
  **/
  @ApiModelProperty(value = "documentNumber")
  public String getDocumentNumber() {
    return documentNumber;
  }

  public void setDocumentNumber(String documentNumber) {
    this.documentNumber = documentNumber;
  }

  public CustomerIdentificationDocument issueLocation(String issueLocation) {
    this.issueLocation = issueLocation;
    return this;
  }

   /**
   * issueLocation
   * @return issueLocation
  **/
  @ApiModelProperty(value = "issueLocation")
  public String getIssueLocation() {
    return issueLocation;
  }

  public void setIssueLocation(String issueLocation) {
    this.issueLocation = issueLocation;
  }

  public CustomerIdentificationDocument issueProvince(String issueProvince) {
    this.issueProvince = issueProvince;
    return this;
  }

   /**
   * issueProvince
   * @return issueProvince
  **/
  @ApiModelProperty(value = "issueProvince")
  public String getIssueProvince() {
    return issueProvince;
  }

  public void setIssueProvince(String issueProvince) {
    this.issueProvince = issueProvince;
  }

  public CustomerIdentificationDocument issueNation(String issueNation) {
    this.issueNation = issueNation;
    return this;
  }

   /**
   * issueNation
   * @return issueNation
  **/
  @ApiModelProperty(value = "issueNation")
  public String getIssueNation() {
    return issueNation;
  }

  public void setIssueNation(String issueNation) {
    this.issueNation = issueNation;
  }

  public CustomerIdentificationDocument issueDate(LocalDate issueDate) {
    this.issueDate = issueDate;
    return this;
  }

   /**
   * issueDate
   * @return issueDate
  **/
  @ApiModelProperty(value = "issueDate")
  public LocalDate getIssueDate() {
    return issueDate;
  }

  public void setIssueDate(LocalDate issueDate) {
    this.issueDate = issueDate;
  }

  public CustomerIdentificationDocument expirationDate(LocalDate expirationDate) {
    this.expirationDate = expirationDate;
    return this;
  }

   /**
   * expirationDate
   * @return expirationDate
  **/
  @ApiModelProperty(value = "expirationDate")
  public LocalDate getExpirationDate() {
    return expirationDate;
  }

  public void setExpirationDate(LocalDate expirationDate) {
    this.expirationDate = expirationDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerIdentificationDocument customerIdentificationDocument = (CustomerIdentificationDocument) o;
    return Objects.equals(this.documentType, customerIdentificationDocument.documentType) &&
        Objects.equals(this.documentNumber, customerIdentificationDocument.documentNumber) &&
        Objects.equals(this.issueLocation, customerIdentificationDocument.issueLocation) &&
        Objects.equals(this.issueProvince, customerIdentificationDocument.issueProvince) &&
        Objects.equals(this.issueNation, customerIdentificationDocument.issueNation) &&
        Objects.equals(this.issueDate, customerIdentificationDocument.issueDate) &&
        Objects.equals(this.expirationDate, customerIdentificationDocument.expirationDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(documentType, documentNumber, issueLocation, issueProvince, issueNation, issueDate, expirationDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerIdentificationDocument {\n");
    
    sb.append("    documentType: ").append(toIndentedString(documentType)).append("\n");
    sb.append("    documentNumber: ").append(toIndentedString(documentNumber)).append("\n");
    sb.append("    issueLocation: ").append(toIndentedString(issueLocation)).append("\n");
    sb.append("    issueProvince: ").append(toIndentedString(issueProvince)).append("\n");
    sb.append("    issueNation: ").append(toIndentedString(issueNation)).append("\n");
    sb.append("    issueDate: ").append(toIndentedString(issueDate)).append("\n");
    sb.append("    expirationDate: ").append(toIndentedString(expirationDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

