/*
 * Customer Reliability
 *  <b>Customer Reliability</b>  
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.AddressExtended;
import io.swagger.client.model.Amount;
import io.swagger.client.model.CompanyBasicData;
import io.swagger.client.model.CustomerData;
import io.swagger.client.model.Mandate;
import java.util.ArrayList;
import java.util.List;

/**
 * Exponent
 */

public class Exponent {
  @JsonProperty("companyInfo")
  private CompanyBasicData companyInfo = null;

  @JsonProperty("anagraphicalData")
  private CustomerData anagraphicalData = null;

  @JsonProperty("address")
  private AddressExtended address = null;

  @JsonProperty("crifNumber")
  private String crifNumber = null;

  @JsonProperty("roleCode")
  private String roleCode = null;

  @JsonProperty("roleDescription")
  private String roleDescription = null;

  @JsonProperty("cab")
  private String cab = null;

  @JsonProperty("cciaaCode")
  private String cciaaCode = null;

  @JsonProperty("reaCode")
  private String reaCode = null;

  @JsonProperty("legalNature")
  private String legalNature = null;

  @JsonProperty("companyParticipation")
  private String companyParticipation = null;

  @JsonProperty("flagPrejudicialDeeds")
  private Boolean flagPrejudicialDeeds = null;

  @JsonProperty("flagProtests")
  private Boolean flagProtests = null;

  @JsonProperty("mandates")
  private List<Mandate> mandates = null;

  @JsonProperty("administrator")
  private String administrator = null;

  @JsonProperty("flagAdministrator")
  private String flagAdministrator = null;

  @JsonProperty("flagSignPower")
  private Boolean flagSignPower = null;

  @JsonProperty("flagReaRapresentative")
  private Boolean flagReaRapresentative = null;

  @JsonProperty("flagRiRapresentative")
  private Boolean flagRiRapresentative = null;

  @JsonProperty("capitalStake")
  private Amount capitalStake = null;

  @JsonProperty("capitalStakePercentage")
  private String capitalStakePercentage = null;

  @JsonProperty("totalShare")
  private Amount totalShare = null;

  @JsonProperty("flagExistBankruptcyProceedings.")
  private Boolean flagExistBankruptcyProceedings_ = null;

  @JsonProperty("flagExistPrejudicialDeeds")
  private Boolean flagExistPrejudicialDeeds = null;

  @JsonProperty("flagExistVerifiedProtests")
  private Boolean flagExistVerifiedProtests = null;

  @JsonProperty("flagExistProtests")
  private Boolean flagExistProtests = null;

  @JsonProperty("flagExistHomonimousProtests")
  private Boolean flagExistHomonimousProtests = null;

  @JsonProperty("flagExistNews")
  private Boolean flagExistNews = null;

  public Exponent companyInfo(CompanyBasicData companyInfo) {
    this.companyInfo = companyInfo;
    return this;
  }

   /**
   * Get companyInfo
   * @return companyInfo
  **/
  @ApiModelProperty(value = "")
  public CompanyBasicData getCompanyInfo() {
    return companyInfo;
  }

  public void setCompanyInfo(CompanyBasicData companyInfo) {
    this.companyInfo = companyInfo;
  }

  public Exponent anagraphicalData(CustomerData anagraphicalData) {
    this.anagraphicalData = anagraphicalData;
    return this;
  }

   /**
   * Get anagraphicalData
   * @return anagraphicalData
  **/
  @ApiModelProperty(value = "")
  public CustomerData getAnagraphicalData() {
    return anagraphicalData;
  }

  public void setAnagraphicalData(CustomerData anagraphicalData) {
    this.anagraphicalData = anagraphicalData;
  }

  public Exponent address(AddressExtended address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @ApiModelProperty(value = "")
  public AddressExtended getAddress() {
    return address;
  }

  public void setAddress(AddressExtended address) {
    this.address = address;
  }

  public Exponent crifNumber(String crifNumber) {
    this.crifNumber = crifNumber;
    return this;
  }

   /**
   * crif number
   * @return crifNumber
  **/
  @ApiModelProperty(example = "12345", value = "crif number")
  public String getCrifNumber() {
    return crifNumber;
  }

  public void setCrifNumber(String crifNumber) {
    this.crifNumber = crifNumber;
  }

  public Exponent roleCode(String roleCode) {
    this.roleCode = roleCode;
    return this;
  }

   /**
   * role code of beneficial owner
   * @return roleCode
  **/
  @ApiModelProperty(value = "role code of beneficial owner")
  public String getRoleCode() {
    return roleCode;
  }

  public void setRoleCode(String roleCode) {
    this.roleCode = roleCode;
  }

  public Exponent roleDescription(String roleDescription) {
    this.roleDescription = roleDescription;
    return this;
  }

   /**
   * role description of beneficial owner
   * @return roleDescription
  **/
  @ApiModelProperty(value = "role description of beneficial owner")
  public String getRoleDescription() {
    return roleDescription;
  }

  public void setRoleDescription(String roleDescription) {
    this.roleDescription = roleDescription;
  }

  public Exponent cab(String cab) {
    this.cab = cab;
    return this;
  }

   /**
   * role description of beneficial owner
   * @return cab
  **/
  @ApiModelProperty(value = "role description of beneficial owner")
  public String getCab() {
    return cab;
  }

  public void setCab(String cab) {
    this.cab = cab;
  }

  public Exponent cciaaCode(String cciaaCode) {
    this.cciaaCode = cciaaCode;
    return this;
  }

   /**
   * cciaa code beneficial owner
   * @return cciaaCode
  **/
  @ApiModelProperty(value = "cciaa code beneficial owner")
  public String getCciaaCode() {
    return cciaaCode;
  }

  public void setCciaaCode(String cciaaCode) {
    this.cciaaCode = cciaaCode;
  }

  public Exponent reaCode(String reaCode) {
    this.reaCode = reaCode;
    return this;
  }

   /**
   * rea code beneficial owner
   * @return reaCode
  **/
  @ApiModelProperty(value = "rea code beneficial owner")
  public String getReaCode() {
    return reaCode;
  }

  public void setReaCode(String reaCode) {
    this.reaCode = reaCode;
  }

  public Exponent legalNature(String legalNature) {
    this.legalNature = legalNature;
    return this;
  }

   /**
   * legal nature of beneficial owner
   * @return legalNature
  **/
  @ApiModelProperty(value = "legal nature of beneficial owner")
  public String getLegalNature() {
    return legalNature;
  }

  public void setLegalNature(String legalNature) {
    this.legalNature = legalNature;
  }

  public Exponent companyParticipation(String companyParticipation) {
    this.companyParticipation = companyParticipation;
    return this;
  }

   /**
   * company participation of beneficial owner
   * @return companyParticipation
  **/
  @ApiModelProperty(value = "company participation of beneficial owner")
  public String getCompanyParticipation() {
    return companyParticipation;
  }

  public void setCompanyParticipation(String companyParticipation) {
    this.companyParticipation = companyParticipation;
  }

  public Exponent flagPrejudicialDeeds(Boolean flagPrejudicialDeeds) {
    this.flagPrejudicialDeeds = flagPrejudicialDeeds;
    return this;
  }

   /**
   * flag that indicate presence of Prejudicial Deeds
   * @return flagPrejudicialDeeds
  **/
  @ApiModelProperty(example = "false", value = "flag that indicate presence of Prejudicial Deeds")
  public Boolean isFlagPrejudicialDeeds() {
    return flagPrejudicialDeeds;
  }

  public void setFlagPrejudicialDeeds(Boolean flagPrejudicialDeeds) {
    this.flagPrejudicialDeeds = flagPrejudicialDeeds;
  }

  public Exponent flagProtests(Boolean flagProtests) {
    this.flagProtests = flagProtests;
    return this;
  }

   /**
   * flag that indicate presence of protests
   * @return flagProtests
  **/
  @ApiModelProperty(example = "false", value = "flag that indicate presence of protests")
  public Boolean isFlagProtests() {
    return flagProtests;
  }

  public void setFlagProtests(Boolean flagProtests) {
    this.flagProtests = flagProtests;
  }

  public Exponent mandates(List<Mandate> mandates) {
    this.mandates = mandates;
    return this;
  }

  public Exponent addMandatesItem(Mandate mandatesItem) {
    if (this.mandates == null) {
      this.mandates = new ArrayList<>();
    }
    this.mandates.add(mandatesItem);
    return this;
  }

   /**
   * Get mandates
   * @return mandates
  **/
  @ApiModelProperty(value = "")
  public List<Mandate> getMandates() {
    return mandates;
  }

  public void setMandates(List<Mandate> mandates) {
    this.mandates = mandates;
  }

  public Exponent administrator(String administrator) {
    this.administrator = administrator;
    return this;
  }

   /**
   * administrator
   * @return administrator
  **/
  @ApiModelProperty(value = "administrator")
  public String getAdministrator() {
    return administrator;
  }

  public void setAdministrator(String administrator) {
    this.administrator = administrator;
  }

  public Exponent flagAdministrator(String flagAdministrator) {
    this.flagAdministrator = flagAdministrator;
    return this;
  }

   /**
   * administrator
   * @return flagAdministrator
  **/
  @ApiModelProperty(value = "administrator")
  public String getFlagAdministrator() {
    return flagAdministrator;
  }

  public void setFlagAdministrator(String flagAdministrator) {
    this.flagAdministrator = flagAdministrator;
  }

  public Exponent flagSignPower(Boolean flagSignPower) {
    this.flagSignPower = flagSignPower;
    return this;
  }

   /**
   * sign power
   * @return flagSignPower
  **/
  @ApiModelProperty(example = "false", value = "sign power")
  public Boolean isFlagSignPower() {
    return flagSignPower;
  }

  public void setFlagSignPower(Boolean flagSignPower) {
    this.flagSignPower = flagSignPower;
  }

  public Exponent flagReaRapresentative(Boolean flagReaRapresentative) {
    this.flagReaRapresentative = flagReaRapresentative;
    return this;
  }

   /**
   * flag rapresentative
   * @return flagReaRapresentative
  **/
  @ApiModelProperty(example = "false", value = "flag rapresentative")
  public Boolean isFlagReaRapresentative() {
    return flagReaRapresentative;
  }

  public void setFlagReaRapresentative(Boolean flagReaRapresentative) {
    this.flagReaRapresentative = flagReaRapresentative;
  }

  public Exponent flagRiRapresentative(Boolean flagRiRapresentative) {
    this.flagRiRapresentative = flagRiRapresentative;
    return this;
  }

   /**
   * flag rapresentative
   * @return flagRiRapresentative
  **/
  @ApiModelProperty(example = "false", value = "flag rapresentative")
  public Boolean isFlagRiRapresentative() {
    return flagRiRapresentative;
  }

  public void setFlagRiRapresentative(Boolean flagRiRapresentative) {
    this.flagRiRapresentative = flagRiRapresentative;
  }

  public Exponent capitalStake(Amount capitalStake) {
    this.capitalStake = capitalStake;
    return this;
  }

   /**
   * capital stake in company
   * @return capitalStake
  **/
  @ApiModelProperty(value = "capital stake in company")
  public Amount getCapitalStake() {
    return capitalStake;
  }

  public void setCapitalStake(Amount capitalStake) {
    this.capitalStake = capitalStake;
  }

  public Exponent capitalStakePercentage(String capitalStakePercentage) {
    this.capitalStakePercentage = capitalStakePercentage;
    return this;
  }

   /**
   * capital stake percentage in company
   * @return capitalStakePercentage
  **/
  @ApiModelProperty(value = "capital stake percentage in company")
  public String getCapitalStakePercentage() {
    return capitalStakePercentage;
  }

  public void setCapitalStakePercentage(String capitalStakePercentage) {
    this.capitalStakePercentage = capitalStakePercentage;
  }

  public Exponent totalShare(Amount totalShare) {
    this.totalShare = totalShare;
    return this;
  }

   /**
   * total share in company
   * @return totalShare
  **/
  @ApiModelProperty(value = "total share in company")
  public Amount getTotalShare() {
    return totalShare;
  }

  public void setTotalShare(Amount totalShare) {
    this.totalShare = totalShare;
  }

  public Exponent flagExistBankruptcyProceedings_(Boolean flagExistBankruptcyProceedings_) {
    this.flagExistBankruptcyProceedings_ = flagExistBankruptcyProceedings_;
    return this;
  }

   /**
   * flag that indicate extisting of bankruptcy proceedings
   * @return flagExistBankruptcyProceedings_
  **/
  @ApiModelProperty(example = "false", value = "flag that indicate extisting of bankruptcy proceedings")
  public Boolean isFlagExistBankruptcyProceedings_() {
    return flagExistBankruptcyProceedings_;
  }

  public void setFlagExistBankruptcyProceedings_(Boolean flagExistBankruptcyProceedings_) {
    this.flagExistBankruptcyProceedings_ = flagExistBankruptcyProceedings_;
  }

  public Exponent flagExistPrejudicialDeeds(Boolean flagExistPrejudicialDeeds) {
    this.flagExistPrejudicialDeeds = flagExistPrejudicialDeeds;
    return this;
  }

   /**
   * flag that indicate presence of Prejudicial Deeds
   * @return flagExistPrejudicialDeeds
  **/
  @ApiModelProperty(example = "false", value = "flag that indicate presence of Prejudicial Deeds")
  public Boolean isFlagExistPrejudicialDeeds() {
    return flagExistPrejudicialDeeds;
  }

  public void setFlagExistPrejudicialDeeds(Boolean flagExistPrejudicialDeeds) {
    this.flagExistPrejudicialDeeds = flagExistPrejudicialDeeds;
  }

  public Exponent flagExistVerifiedProtests(Boolean flagExistVerifiedProtests) {
    this.flagExistVerifiedProtests = flagExistVerifiedProtests;
    return this;
  }

   /**
   * flag that indicate presence of VerifiedProtests
   * @return flagExistVerifiedProtests
  **/
  @ApiModelProperty(example = "false", value = "flag that indicate presence of VerifiedProtests")
  public Boolean isFlagExistVerifiedProtests() {
    return flagExistVerifiedProtests;
  }

  public void setFlagExistVerifiedProtests(Boolean flagExistVerifiedProtests) {
    this.flagExistVerifiedProtests = flagExistVerifiedProtests;
  }

  public Exponent flagExistProtests(Boolean flagExistProtests) {
    this.flagExistProtests = flagExistProtests;
    return this;
  }

   /**
   * flag that indicate presence of Protests
   * @return flagExistProtests
  **/
  @ApiModelProperty(example = "false", value = "flag that indicate presence of Protests")
  public Boolean isFlagExistProtests() {
    return flagExistProtests;
  }

  public void setFlagExistProtests(Boolean flagExistProtests) {
    this.flagExistProtests = flagExistProtests;
  }

  public Exponent flagExistHomonimousProtests(Boolean flagExistHomonimousProtests) {
    this.flagExistHomonimousProtests = flagExistHomonimousProtests;
    return this;
  }

   /**
   * flag exist homonimous protests
   * @return flagExistHomonimousProtests
  **/
  @ApiModelProperty(example = "false", value = "flag exist homonimous protests")
  public Boolean isFlagExistHomonimousProtests() {
    return flagExistHomonimousProtests;
  }

  public void setFlagExistHomonimousProtests(Boolean flagExistHomonimousProtests) {
    this.flagExistHomonimousProtests = flagExistHomonimousProtests;
  }

  public Exponent flagExistNews(Boolean flagExistNews) {
    this.flagExistNews = flagExistNews;
    return this;
  }

   /**
   * flag exist news
   * @return flagExistNews
  **/
  @ApiModelProperty(example = "false", value = "flag exist news")
  public Boolean isFlagExistNews() {
    return flagExistNews;
  }

  public void setFlagExistNews(Boolean flagExistNews) {
    this.flagExistNews = flagExistNews;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Exponent exponent = (Exponent) o;
    return Objects.equals(this.companyInfo, exponent.companyInfo) &&
        Objects.equals(this.anagraphicalData, exponent.anagraphicalData) &&
        Objects.equals(this.address, exponent.address) &&
        Objects.equals(this.crifNumber, exponent.crifNumber) &&
        Objects.equals(this.roleCode, exponent.roleCode) &&
        Objects.equals(this.roleDescription, exponent.roleDescription) &&
        Objects.equals(this.cab, exponent.cab) &&
        Objects.equals(this.cciaaCode, exponent.cciaaCode) &&
        Objects.equals(this.reaCode, exponent.reaCode) &&
        Objects.equals(this.legalNature, exponent.legalNature) &&
        Objects.equals(this.companyParticipation, exponent.companyParticipation) &&
        Objects.equals(this.flagPrejudicialDeeds, exponent.flagPrejudicialDeeds) &&
        Objects.equals(this.flagProtests, exponent.flagProtests) &&
        Objects.equals(this.mandates, exponent.mandates) &&
        Objects.equals(this.administrator, exponent.administrator) &&
        Objects.equals(this.flagAdministrator, exponent.flagAdministrator) &&
        Objects.equals(this.flagSignPower, exponent.flagSignPower) &&
        Objects.equals(this.flagReaRapresentative, exponent.flagReaRapresentative) &&
        Objects.equals(this.flagRiRapresentative, exponent.flagRiRapresentative) &&
        Objects.equals(this.capitalStake, exponent.capitalStake) &&
        Objects.equals(this.capitalStakePercentage, exponent.capitalStakePercentage) &&
        Objects.equals(this.totalShare, exponent.totalShare) &&
        Objects.equals(this.flagExistBankruptcyProceedings_, exponent.flagExistBankruptcyProceedings_) &&
        Objects.equals(this.flagExistPrejudicialDeeds, exponent.flagExistPrejudicialDeeds) &&
        Objects.equals(this.flagExistVerifiedProtests, exponent.flagExistVerifiedProtests) &&
        Objects.equals(this.flagExistProtests, exponent.flagExistProtests) &&
        Objects.equals(this.flagExistHomonimousProtests, exponent.flagExistHomonimousProtests) &&
        Objects.equals(this.flagExistNews, exponent.flagExistNews);
  }

  @Override
  public int hashCode() {
    return Objects.hash(companyInfo, anagraphicalData, address, crifNumber, roleCode, roleDescription, cab, cciaaCode, reaCode, legalNature, companyParticipation, flagPrejudicialDeeds, flagProtests, mandates, administrator, flagAdministrator, flagSignPower, flagReaRapresentative, flagRiRapresentative, capitalStake, capitalStakePercentage, totalShare, flagExistBankruptcyProceedings_, flagExistPrejudicialDeeds, flagExistVerifiedProtests, flagExistProtests, flagExistHomonimousProtests, flagExistNews);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Exponent {\n");
    
    sb.append("    companyInfo: ").append(toIndentedString(companyInfo)).append("\n");
    sb.append("    anagraphicalData: ").append(toIndentedString(anagraphicalData)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    crifNumber: ").append(toIndentedString(crifNumber)).append("\n");
    sb.append("    roleCode: ").append(toIndentedString(roleCode)).append("\n");
    sb.append("    roleDescription: ").append(toIndentedString(roleDescription)).append("\n");
    sb.append("    cab: ").append(toIndentedString(cab)).append("\n");
    sb.append("    cciaaCode: ").append(toIndentedString(cciaaCode)).append("\n");
    sb.append("    reaCode: ").append(toIndentedString(reaCode)).append("\n");
    sb.append("    legalNature: ").append(toIndentedString(legalNature)).append("\n");
    sb.append("    companyParticipation: ").append(toIndentedString(companyParticipation)).append("\n");
    sb.append("    flagPrejudicialDeeds: ").append(toIndentedString(flagPrejudicialDeeds)).append("\n");
    sb.append("    flagProtests: ").append(toIndentedString(flagProtests)).append("\n");
    sb.append("    mandates: ").append(toIndentedString(mandates)).append("\n");
    sb.append("    administrator: ").append(toIndentedString(administrator)).append("\n");
    sb.append("    flagAdministrator: ").append(toIndentedString(flagAdministrator)).append("\n");
    sb.append("    flagSignPower: ").append(toIndentedString(flagSignPower)).append("\n");
    sb.append("    flagReaRapresentative: ").append(toIndentedString(flagReaRapresentative)).append("\n");
    sb.append("    flagRiRapresentative: ").append(toIndentedString(flagRiRapresentative)).append("\n");
    sb.append("    capitalStake: ").append(toIndentedString(capitalStake)).append("\n");
    sb.append("    capitalStakePercentage: ").append(toIndentedString(capitalStakePercentage)).append("\n");
    sb.append("    totalShare: ").append(toIndentedString(totalShare)).append("\n");
    sb.append("    flagExistBankruptcyProceedings_: ").append(toIndentedString(flagExistBankruptcyProceedings_)).append("\n");
    sb.append("    flagExistPrejudicialDeeds: ").append(toIndentedString(flagExistPrejudicialDeeds)).append("\n");
    sb.append("    flagExistVerifiedProtests: ").append(toIndentedString(flagExistVerifiedProtests)).append("\n");
    sb.append("    flagExistProtests: ").append(toIndentedString(flagExistProtests)).append("\n");
    sb.append("    flagExistHomonimousProtests: ").append(toIndentedString(flagExistHomonimousProtests)).append("\n");
    sb.append("    flagExistNews: ").append(toIndentedString(flagExistNews)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

