/*
 * Customer Reliability
 *  <b>Customer Reliability</b>  
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * FraudRiskAnalyserResult
 */

public class FraudRiskAnalyserResult {
  @JsonProperty("range")
  private String range = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("score")
  private String score = null;

  public FraudRiskAnalyserResult range(String range) {
    this.range = range;
    return this;
  }

   /**
   * score band
   * @return range
  **/
  @ApiModelProperty(value = "score band")
  public String getRange() {
    return range;
  }

  public void setRange(String range) {
    this.range = range;
  }

  public FraudRiskAnalyserResult description(String description) {
    this.description = description;
    return this;
  }

   /**
   * score description
   * @return description
  **/
  @ApiModelProperty(value = "score description")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public FraudRiskAnalyserResult score(String score) {
    this.score = score;
    return this;
  }

   /**
   * score Point value
   * @return score
  **/
  @ApiModelProperty(value = "score Point value")
  public String getScore() {
    return score;
  }

  public void setScore(String score) {
    this.score = score;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FraudRiskAnalyserResult fraudRiskAnalyserResult = (FraudRiskAnalyserResult) o;
    return Objects.equals(this.range, fraudRiskAnalyserResult.range) &&
        Objects.equals(this.description, fraudRiskAnalyserResult.description) &&
        Objects.equals(this.score, fraudRiskAnalyserResult.score);
  }

  @Override
  public int hashCode() {
    return Objects.hash(range, description, score);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FraudRiskAnalyserResult {\n");
    
    sb.append("    range: ").append(toIndentedString(range)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    score: ").append(toIndentedString(score)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

