/*
 * Customer Reliability
 *  <b>Customer Reliability</b>  
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.BaseRequest;

/**
 * GetCustomerReliabilityResultRequest
 */

public class GetCustomerReliabilityResultRequest {
  @JsonProperty("registryVerificationId")
  private String registryVerificationId = null;

  public GetCustomerReliabilityResultRequest registryVerificationId(String registryVerificationId) {
    this.registryVerificationId = registryVerificationId;
    return this;
  }

   /**
   * registryVerificationId
   * @return registryVerificationId
  **/
  @ApiModelProperty(value = "registryVerificationId")
  public String getRegistryVerificationId() {
    return registryVerificationId;
  }

  public void setRegistryVerificationId(String registryVerificationId) {
    this.registryVerificationId = registryVerificationId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetCustomerReliabilityResultRequest getCustomerReliabilityResultRequest = (GetCustomerReliabilityResultRequest) o;
    return Objects.equals(this.registryVerificationId, getCustomerReliabilityResultRequest.registryVerificationId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(registryVerificationId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetCustomerReliabilityResultRequest {\n");
    
    sb.append("    registryVerificationId: ").append(toIndentedString(registryVerificationId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

