/*
 * Customer Reliability
 *  <b>Customer Reliability</b>  
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.BaseRequest;

/**
 * GetCustomerReliabilityDocumentRequest
 */

public class GetCustomerReliabilityDocumentRequest {
  @JsonProperty("messageId")
  private String messageId = null;

  @JsonProperty("serviceId")
  private String serviceId = null;

  @JsonProperty("productId")
  private String productId = null;

  @JsonProperty("language")
  private String language = null;

  @JsonProperty("presentationNameSpace")
  private String presentationNameSpace = null;

  @JsonProperty("compressionType")
  private String compressionType = null;

  @JsonProperty("formatId")
  private String formatId = null;

  public GetCustomerReliabilityDocumentRequest messageId(String messageId) {
    this.messageId = messageId;
    return this;
  }

   /**
   * messageId
   * @return messageId
  **/
  @ApiModelProperty(value = "messageId")
  public String getMessageId() {
    return messageId;
  }

  public void setMessageId(String messageId) {
    this.messageId = messageId;
  }

  public GetCustomerReliabilityDocumentRequest serviceId(String serviceId) {
    this.serviceId = serviceId;
    return this;
  }

   /**
   * serviceId
   * @return serviceId
  **/
  @ApiModelProperty(value = "serviceId")
  public String getServiceId() {
    return serviceId;
  }

  public void setServiceId(String serviceId) {
    this.serviceId = serviceId;
  }

  public GetCustomerReliabilityDocumentRequest productId(String productId) {
    this.productId = productId;
    return this;
  }

   /**
   * productId
   * @return productId
  **/
  @ApiModelProperty(value = "productId")
  public String getProductId() {
    return productId;
  }

  public void setProductId(String productId) {
    this.productId = productId;
  }

  public GetCustomerReliabilityDocumentRequest language(String language) {
    this.language = language;
    return this;
  }

   /**
   * language
   * @return language
  **/
  @ApiModelProperty(value = "language")
  public String getLanguage() {
    return language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }

  public GetCustomerReliabilityDocumentRequest presentationNameSpace(String presentationNameSpace) {
    this.presentationNameSpace = presentationNameSpace;
    return this;
  }

   /**
   * presentationNameSpace
   * @return presentationNameSpace
  **/
  @ApiModelProperty(value = "presentationNameSpace")
  public String getPresentationNameSpace() {
    return presentationNameSpace;
  }

  public void setPresentationNameSpace(String presentationNameSpace) {
    this.presentationNameSpace = presentationNameSpace;
  }

  public GetCustomerReliabilityDocumentRequest compressionType(String compressionType) {
    this.compressionType = compressionType;
    return this;
  }

   /**
   * compressionType
   * @return compressionType
  **/
  @ApiModelProperty(value = "compressionType")
  public String getCompressionType() {
    return compressionType;
  }

  public void setCompressionType(String compressionType) {
    this.compressionType = compressionType;
  }

  public GetCustomerReliabilityDocumentRequest formatId(String formatId) {
    this.formatId = formatId;
    return this;
  }

   /**
   * formatId
   * @return formatId
  **/
  @ApiModelProperty(value = "formatId")
  public String getFormatId() {
    return formatId;
  }

  public void setFormatId(String formatId) {
    this.formatId = formatId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetCustomerReliabilityDocumentRequest getCustomerReliabilityDocumentRequest = (GetCustomerReliabilityDocumentRequest) o;
    return Objects.equals(this.messageId, getCustomerReliabilityDocumentRequest.messageId) &&
        Objects.equals(this.serviceId, getCustomerReliabilityDocumentRequest.serviceId) &&
        Objects.equals(this.productId, getCustomerReliabilityDocumentRequest.productId) &&
        Objects.equals(this.language, getCustomerReliabilityDocumentRequest.language) &&
        Objects.equals(this.presentationNameSpace, getCustomerReliabilityDocumentRequest.presentationNameSpace) &&
        Objects.equals(this.compressionType, getCustomerReliabilityDocumentRequest.compressionType) &&
        Objects.equals(this.formatId, getCustomerReliabilityDocumentRequest.formatId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(messageId, serviceId, productId, language, presentationNameSpace, compressionType, formatId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetCustomerReliabilityDocumentRequest {\n");
    
    sb.append("    messageId: ").append(toIndentedString(messageId)).append("\n");
    sb.append("    serviceId: ").append(toIndentedString(serviceId)).append("\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    presentationNameSpace: ").append(toIndentedString(presentationNameSpace)).append("\n");
    sb.append("    compressionType: ").append(toIndentedString(compressionType)).append("\n");
    sb.append("    formatId: ").append(toIndentedString(formatId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

