/*
 * Customer Reliability
 *  <b>Customer Reliability</b>  
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.BaseRequest;
import io.swagger.client.model.CardId;
import java.util.ArrayList;
import java.util.List;

/**
 * GetCustomerDocumentRequest
 */

public class GetCustomerDocumentRequest {
  @JsonProperty("cardId")
  private List<CardId> cardId = null;

  @JsonProperty("positionId")
  private String positionId = null;

  @JsonProperty("positionKeySion")
  private String positionKeySion = null;

  public GetCustomerDocumentRequest cardId(List<CardId> cardId) {
    this.cardId = cardId;
    return this;
  }

  public GetCustomerDocumentRequest addCardIdItem(CardId cardIdItem) {
    if (this.cardId == null) {
      this.cardId = new ArrayList<>();
    }
    this.cardId.add(cardIdItem);
    return this;
  }

   /**
   * Get cardId
   * @return cardId
  **/
  @ApiModelProperty(value = "")
  public List<CardId> getCardId() {
    return cardId;
  }

  public void setCardId(List<CardId> cardId) {
    this.cardId = cardId;
  }

  public GetCustomerDocumentRequest positionId(String positionId) {
    this.positionId = positionId;
    return this;
  }

   /**
   * identification number of the position
   * @return positionId
  **/
  @ApiModelProperty(example = "0001152", value = "identification number of the position")
  public String getPositionId() {
    return positionId;
  }

  public void setPositionId(String positionId) {
    this.positionId = positionId;
  }

  public GetCustomerDocumentRequest positionKeySion(String positionKeySion) {
    this.positionKeySion = positionKeySion;
    return this;
  }

   /**
   * identification number of the position
   * @return positionKeySion
  **/
  @ApiModelProperty(example = "0000001152", value = "identification number of the position")
  public String getPositionKeySion() {
    return positionKeySion;
  }

  public void setPositionKeySion(String positionKeySion) {
    this.positionKeySion = positionKeySion;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetCustomerDocumentRequest getCustomerDocumentRequest = (GetCustomerDocumentRequest) o;
    return Objects.equals(this.cardId, getCustomerDocumentRequest.cardId) &&
        Objects.equals(this.positionId, getCustomerDocumentRequest.positionId) &&
        Objects.equals(this.positionKeySion, getCustomerDocumentRequest.positionKeySion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cardId, positionId, positionKeySion);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetCustomerDocumentRequest {\n");
    
    sb.append("    cardId: ").append(toIndentedString(cardId)).append("\n");
    sb.append("    positionId: ").append(toIndentedString(positionId)).append("\n");
    sb.append("    positionKeySion: ").append(toIndentedString(positionKeySion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

