/*
 * Customer Reliability
 *  <b>Customer Reliability</b>  
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.BaseResponse;
import io.swagger.client.model.CompanyDetails;
import io.swagger.client.model.ErrorResult;
import io.swagger.client.model.FraudRiskAlert;
import io.swagger.client.model.Result;
import java.util.ArrayList;
import java.util.List;

/**
 * GetCustomerReliabilityResultResponse
 */

public class GetCustomerReliabilityResultResponse {
  @JsonProperty("result")
  private Result result = null;

  @JsonProperty("registryVerificationId")
  private String registryVerificationId = null;

  @JsonProperty("companyDetails")
  private CompanyDetails companyDetails = null;

  @JsonProperty("fraudRiskAnalyserScore")
  private String fraudRiskAnalyserScore = null;

  @JsonProperty("fraudRiskAlert")
  private List<FraudRiskAlert> fraudRiskAlert = null;

  @JsonProperty("fraudRiskErrors")
  private List<ErrorResult> fraudRiskErrors = null;

  public GetCustomerReliabilityResultResponse result(Result result) {
    this.result = result;
    return this;
  }

   /**
   * Get result
   * @return result
  **/
  @ApiModelProperty(value = "")
  public Result getResult() {
    return result;
  }

  public void setResult(Result result) {
    this.result = result;
  }

  public GetCustomerReliabilityResultResponse registryVerificationId(String registryVerificationId) {
    this.registryVerificationId = registryVerificationId;
    return this;
  }

   /**
   * verificationId
   * @return registryVerificationId
  **/
  @ApiModelProperty(value = "verificationId")
  public String getRegistryVerificationId() {
    return registryVerificationId;
  }

  public void setRegistryVerificationId(String registryVerificationId) {
    this.registryVerificationId = registryVerificationId;
  }

  public GetCustomerReliabilityResultResponse companyDetails(CompanyDetails companyDetails) {
    this.companyDetails = companyDetails;
    return this;
  }

   /**
   * Get companyDetails
   * @return companyDetails
  **/
  @ApiModelProperty(value = "")
  public CompanyDetails getCompanyDetails() {
    return companyDetails;
  }

  public void setCompanyDetails(CompanyDetails companyDetails) {
    this.companyDetails = companyDetails;
  }

  public GetCustomerReliabilityResultResponse fraudRiskAnalyserScore(String fraudRiskAnalyserScore) {
    this.fraudRiskAnalyserScore = fraudRiskAnalyserScore;
    return this;
  }

   /**
   * fraudRiskScore
   * @return fraudRiskAnalyserScore
  **/
  @ApiModelProperty(value = "fraudRiskScore")
  public String getFraudRiskAnalyserScore() {
    return fraudRiskAnalyserScore;
  }

  public void setFraudRiskAnalyserScore(String fraudRiskAnalyserScore) {
    this.fraudRiskAnalyserScore = fraudRiskAnalyserScore;
  }

  public GetCustomerReliabilityResultResponse fraudRiskAlert(List<FraudRiskAlert> fraudRiskAlert) {
    this.fraudRiskAlert = fraudRiskAlert;
    return this;
  }

  public GetCustomerReliabilityResultResponse addFraudRiskAlertItem(FraudRiskAlert fraudRiskAlertItem) {
    if (this.fraudRiskAlert == null) {
      this.fraudRiskAlert = new ArrayList<>();
    }
    this.fraudRiskAlert.add(fraudRiskAlertItem);
    return this;
  }

   /**
   * Get fraudRiskAlert
   * @return fraudRiskAlert
  **/
  @ApiModelProperty(value = "")
  public List<FraudRiskAlert> getFraudRiskAlert() {
    return fraudRiskAlert;
  }

  public void setFraudRiskAlert(List<FraudRiskAlert> fraudRiskAlert) {
    this.fraudRiskAlert = fraudRiskAlert;
  }

  public GetCustomerReliabilityResultResponse fraudRiskErrors(List<ErrorResult> fraudRiskErrors) {
    this.fraudRiskErrors = fraudRiskErrors;
    return this;
  }

  public GetCustomerReliabilityResultResponse addFraudRiskErrorsItem(ErrorResult fraudRiskErrorsItem) {
    if (this.fraudRiskErrors == null) {
      this.fraudRiskErrors = new ArrayList<>();
    }
    this.fraudRiskErrors.add(fraudRiskErrorsItem);
    return this;
  }

   /**
   * Get fraudRiskErrors
   * @return fraudRiskErrors
  **/
  @ApiModelProperty(value = "")
  public List<ErrorResult> getFraudRiskErrors() {
    return fraudRiskErrors;
  }

  public void setFraudRiskErrors(List<ErrorResult> fraudRiskErrors) {
    this.fraudRiskErrors = fraudRiskErrors;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetCustomerReliabilityResultResponse getCustomerReliabilityResultResponse = (GetCustomerReliabilityResultResponse) o;
    return Objects.equals(this.result, getCustomerReliabilityResultResponse.result) &&
        Objects.equals(this.registryVerificationId, getCustomerReliabilityResultResponse.registryVerificationId) &&
        Objects.equals(this.companyDetails, getCustomerReliabilityResultResponse.companyDetails) &&
        Objects.equals(this.fraudRiskAnalyserScore, getCustomerReliabilityResultResponse.fraudRiskAnalyserScore) &&
        Objects.equals(this.fraudRiskAlert, getCustomerReliabilityResultResponse.fraudRiskAlert) &&
        Objects.equals(this.fraudRiskErrors, getCustomerReliabilityResultResponse.fraudRiskErrors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(result, registryVerificationId, companyDetails, fraudRiskAnalyserScore, fraudRiskAlert, fraudRiskErrors);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetCustomerReliabilityResultResponse {\n");
    
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    registryVerificationId: ").append(toIndentedString(registryVerificationId)).append("\n");
    sb.append("    companyDetails: ").append(toIndentedString(companyDetails)).append("\n");
    sb.append("    fraudRiskAnalyserScore: ").append(toIndentedString(fraudRiskAnalyserScore)).append("\n");
    sb.append("    fraudRiskAlert: ").append(toIndentedString(fraudRiskAlert)).append("\n");
    sb.append("    fraudRiskErrors: ").append(toIndentedString(fraudRiskErrors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

