/*
 * Customer Reliability
 *  <b>Customer Reliability</b>  
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Address;
import io.swagger.client.model.BaseRequest;
import io.swagger.client.model.CompanyBasicData;
import io.swagger.client.model.IndividualCompanyData;
import java.util.ArrayList;
import java.util.List;

/**
 * GetCompanyReliabilityReportRequest
 */

public class GetCompanyReliabilityReportRequest {
  @JsonProperty("companyData")
  private CompanyBasicData companyData = null;

  @JsonProperty("individualCompanyData")
  private IndividualCompanyData individualCompanyData = null;

  @JsonProperty("addresses")
  private List<Address> addresses = null;

  @JsonProperty("reportTypeCode")
  private String reportTypeCode = null;

  public GetCompanyReliabilityReportRequest companyData(CompanyBasicData companyData) {
    this.companyData = companyData;
    return this;
  }

   /**
   * company Data
   * @return companyData
  **/
  @ApiModelProperty(value = "company Data")
  public CompanyBasicData getCompanyData() {
    return companyData;
  }

  public void setCompanyData(CompanyBasicData companyData) {
    this.companyData = companyData;
  }

  public GetCompanyReliabilityReportRequest individualCompanyData(IndividualCompanyData individualCompanyData) {
    this.individualCompanyData = individualCompanyData;
    return this;
  }

   /**
   * individual company data
   * @return individualCompanyData
  **/
  @ApiModelProperty(value = "individual company data")
  public IndividualCompanyData getIndividualCompanyData() {
    return individualCompanyData;
  }

  public void setIndividualCompanyData(IndividualCompanyData individualCompanyData) {
    this.individualCompanyData = individualCompanyData;
  }

  public GetCompanyReliabilityReportRequest addresses(List<Address> addresses) {
    this.addresses = addresses;
    return this;
  }

  public GetCompanyReliabilityReportRequest addAddressesItem(Address addressesItem) {
    if (this.addresses == null) {
      this.addresses = new ArrayList<>();
    }
    this.addresses.add(addressesItem);
    return this;
  }

   /**
   * Get addresses
   * @return addresses
  **/
  @ApiModelProperty(value = "")
  public List<Address> getAddresses() {
    return addresses;
  }

  public void setAddresses(List<Address> addresses) {
    this.addresses = addresses;
  }

  public GetCompanyReliabilityReportRequest reportTypeCode(String reportTypeCode) {
    this.reportTypeCode = reportTypeCode;
    return this;
  }

   /**
   * Report type required
   * @return reportTypeCode
  **/
  @ApiModelProperty(example = "FComCard", value = "Report type required")
  public String getReportTypeCode() {
    return reportTypeCode;
  }

  public void setReportTypeCode(String reportTypeCode) {
    this.reportTypeCode = reportTypeCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetCompanyReliabilityReportRequest getCompanyReliabilityReportRequest = (GetCompanyReliabilityReportRequest) o;
    return Objects.equals(this.companyData, getCompanyReliabilityReportRequest.companyData) &&
        Objects.equals(this.individualCompanyData, getCompanyReliabilityReportRequest.individualCompanyData) &&
        Objects.equals(this.addresses, getCompanyReliabilityReportRequest.addresses) &&
        Objects.equals(this.reportTypeCode, getCompanyReliabilityReportRequest.reportTypeCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(companyData, individualCompanyData, addresses, reportTypeCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetCompanyReliabilityReportRequest {\n");
    
    sb.append("    companyData: ").append(toIndentedString(companyData)).append("\n");
    sb.append("    individualCompanyData: ").append(toIndentedString(individualCompanyData)).append("\n");
    sb.append("    addresses: ").append(toIndentedString(addresses)).append("\n");
    sb.append("    reportTypeCode: ").append(toIndentedString(reportTypeCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

