/*
 * Customer Reliability
 *  <b>Customer Reliability</b>  
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.BaseResponse;
import io.swagger.client.model.CustomerDocument;
import io.swagger.client.model.Result;
import java.util.ArrayList;
import java.util.List;

/**
 * GetCustomerDocumentResponse
 */

public class GetCustomerDocumentResponse {
  @JsonProperty("result")
  private Result result = null;

  @JsonProperty("positionKeySion")
  private String positionKeySion = null;

  @JsonProperty("documents")
  private List<CustomerDocument> documents = null;

  public GetCustomerDocumentResponse result(Result result) {
    this.result = result;
    return this;
  }

   /**
   * Get result
   * @return result
  **/
  @ApiModelProperty(value = "")
  public Result getResult() {
    return result;
  }

  public void setResult(Result result) {
    this.result = result;
  }

  public GetCustomerDocumentResponse positionKeySion(String positionKeySion) {
    this.positionKeySion = positionKeySion;
    return this;
  }

   /**
   * identification number of the position
   * @return positionKeySion
  **/
  @ApiModelProperty(example = "0000001152", value = "identification number of the position")
  public String getPositionKeySion() {
    return positionKeySion;
  }

  public void setPositionKeySion(String positionKeySion) {
    this.positionKeySion = positionKeySion;
  }

  public GetCustomerDocumentResponse documents(List<CustomerDocument> documents) {
    this.documents = documents;
    return this;
  }

  public GetCustomerDocumentResponse addDocumentsItem(CustomerDocument documentsItem) {
    if (this.documents == null) {
      this.documents = new ArrayList<>();
    }
    this.documents.add(documentsItem);
    return this;
  }

   /**
   * Get documents
   * @return documents
  **/
  @ApiModelProperty(value = "")
  public List<CustomerDocument> getDocuments() {
    return documents;
  }

  public void setDocuments(List<CustomerDocument> documents) {
    this.documents = documents;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetCustomerDocumentResponse getCustomerDocumentResponse = (GetCustomerDocumentResponse) o;
    return Objects.equals(this.result, getCustomerDocumentResponse.result) &&
        Objects.equals(this.positionKeySion, getCustomerDocumentResponse.positionKeySion) &&
        Objects.equals(this.documents, getCustomerDocumentResponse.documents);
  }

  @Override
  public int hashCode() {
    return Objects.hash(result, positionKeySion, documents);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetCustomerDocumentResponse {\n");
    
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    positionKeySion: ").append(toIndentedString(positionKeySion)).append("\n");
    sb.append("    documents: ").append(toIndentedString(documents)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

