/*
 * Notification API
 * <b>Notification</b>  
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.BaseResponse;
import io.swagger.client.model.EmailTrackingDetails;
import io.swagger.client.model.PaginationOut;
import io.swagger.client.model.Result;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * GetEmailTrackingDetailsResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-05T15:49:18.314Z")
public class GetEmailTrackingDetailsResponse extends BaseResponse {
  @SerializedName("emailTrakingDetails")
  private List<EmailTrackingDetails> emailTrakingDetails = null;

  @SerializedName("paginationOut")
  private PaginationOut paginationOut = null;

  public GetEmailTrackingDetailsResponse emailTrakingDetails(List<EmailTrackingDetails> emailTrakingDetails) {
    this.emailTrakingDetails = emailTrakingDetails;
    return this;
  }

  public GetEmailTrackingDetailsResponse addEmailTrakingDetailsItem(EmailTrackingDetails emailTrakingDetailsItem) {
    if (this.emailTrakingDetails == null) {
      this.emailTrakingDetails = new ArrayList<EmailTrackingDetails>();
    }
    this.emailTrakingDetails.add(emailTrakingDetailsItem);
    return this;
  }

   /**
   * email tracking details list
   * @return emailTrakingDetails
  **/
  @ApiModelProperty(value = "email tracking details list")
  public List<EmailTrackingDetails> getEmailTrakingDetails() {
    return emailTrakingDetails;
  }

  public void setEmailTrakingDetails(List<EmailTrackingDetails> emailTrakingDetails) {
    this.emailTrakingDetails = emailTrakingDetails;
  }

  public GetEmailTrackingDetailsResponse paginationOut(PaginationOut paginationOut) {
    this.paginationOut = paginationOut;
    return this;
  }

   /**
   * pagination out
   * @return paginationOut
  **/
  @ApiModelProperty(value = "pagination out")
  public PaginationOut getPaginationOut() {
    return paginationOut;
  }

  public void setPaginationOut(PaginationOut paginationOut) {
    this.paginationOut = paginationOut;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetEmailTrackingDetailsResponse getEmailTrackingDetailsResponse = (GetEmailTrackingDetailsResponse) o;
    return Objects.equals(this.emailTrakingDetails, getEmailTrackingDetailsResponse.emailTrakingDetails) &&
        Objects.equals(this.paginationOut, getEmailTrackingDetailsResponse.paginationOut) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(emailTrakingDetails, paginationOut, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetEmailTrackingDetailsResponse {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    emailTrakingDetails: ").append(toIndentedString(emailTrakingDetails)).append("\n");
    sb.append("    paginationOut: ").append(toIndentedString(paginationOut)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

