/*
 * Notification API
 * <b>Notification</b>  
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.BaseRequest;
import io.swagger.client.model.PaginationIn;
import java.io.IOException;
import org.threeten.bp.LocalDate;

/**
 * GetEmailTrackingDetailsRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-05T15:49:18.314Z")
public class GetEmailTrackingDetailsRequest extends BaseRequest {
  @SerializedName("dateFrom")
  private LocalDate dateFrom = null;

  @SerializedName("dateTo")
  private LocalDate dateTo = null;

  @SerializedName("emailTag")
  private String emailTag = null;

  @SerializedName("fromAddress")
  private String fromAddress = null;

  @SerializedName("toAddress")
  private String toAddress = null;

  @SerializedName("ccAddress")
  private String ccAddress = null;

  @SerializedName("templateId")
  private String templateId = null;

  @SerializedName("paginationIn")
  private PaginationIn paginationIn = null;

  public GetEmailTrackingDetailsRequest dateFrom(LocalDate dateFrom) {
    this.dateFrom = dateFrom;
    return this;
  }

   /**
   * start date of range (inclusive)
   * @return dateFrom
  **/
  @ApiModelProperty(value = "start date of range (inclusive)")
  public LocalDate getDateFrom() {
    return dateFrom;
  }

  public void setDateFrom(LocalDate dateFrom) {
    this.dateFrom = dateFrom;
  }

  public GetEmailTrackingDetailsRequest dateTo(LocalDate dateTo) {
    this.dateTo = dateTo;
    return this;
  }

   /**
   * end date of range (inclusive)
   * @return dateTo
  **/
  @ApiModelProperty(value = "end date of range (inclusive)")
  public LocalDate getDateTo() {
    return dateTo;
  }

  public void setDateTo(LocalDate dateTo) {
    this.dateTo = dateTo;
  }

  public GetEmailTrackingDetailsRequest emailTag(String emailTag) {
    this.emailTag = emailTag;
    return this;
  }

   /**
   * email tag filter for search
   * @return emailTag
  **/
  @ApiModelProperty(value = "email tag filter for search")
  public String getEmailTag() {
    return emailTag;
  }

  public void setEmailTag(String emailTag) {
    this.emailTag = emailTag;
  }

  public GetEmailTrackingDetailsRequest fromAddress(String fromAddress) {
    this.fromAddress = fromAddress;
    return this;
  }

   /**
   * email sender address filter for search
   * @return fromAddress
  **/
  @ApiModelProperty(value = "email sender address filter for search")
  public String getFromAddress() {
    return fromAddress;
  }

  public void setFromAddress(String fromAddress) {
    this.fromAddress = fromAddress;
  }

  public GetEmailTrackingDetailsRequest toAddress(String toAddress) {
    this.toAddress = toAddress;
    return this;
  }

   /**
   * email \&quot;to\&quot; address filter for search
   * @return toAddress
  **/
  @ApiModelProperty(value = "email \"to\" address filter for search")
  public String getToAddress() {
    return toAddress;
  }

  public void setToAddress(String toAddress) {
    this.toAddress = toAddress;
  }

  public GetEmailTrackingDetailsRequest ccAddress(String ccAddress) {
    this.ccAddress = ccAddress;
    return this;
  }

   /**
   * email \&quot;cc\&quot; address filter for search
   * @return ccAddress
  **/
  @ApiModelProperty(value = "email \"cc\" address filter for search")
  public String getCcAddress() {
    return ccAddress;
  }

  public void setCcAddress(String ccAddress) {
    this.ccAddress = ccAddress;
  }

  public GetEmailTrackingDetailsRequest templateId(String templateId) {
    this.templateId = templateId;
    return this;
  }

   /**
   * email template id filter for search
   * @return templateId
  **/
  @ApiModelProperty(value = "email template id filter for search")
  public String getTemplateId() {
    return templateId;
  }

  public void setTemplateId(String templateId) {
    this.templateId = templateId;
  }

  public GetEmailTrackingDetailsRequest paginationIn(PaginationIn paginationIn) {
    this.paginationIn = paginationIn;
    return this;
  }

   /**
   * pagination in
   * @return paginationIn
  **/
  @ApiModelProperty(value = "pagination in")
  public PaginationIn getPaginationIn() {
    return paginationIn;
  }

  public void setPaginationIn(PaginationIn paginationIn) {
    this.paginationIn = paginationIn;
  }



  /*public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetEmailTrackingDetailsRequest getEmailTrackingDetailsRequest = (GetEmailTrackingDetailsRequest) o;
    return Objects.equals(this.dateFrom, getEmailTrackingDetailsRequest.dateFrom) &&
        Objects.equals(this.dateTo, getEmailTrackingDetailsRequest.dateTo) &&
        Objects.equals(this.emailTag, getEmailTrackingDetailsRequest.emailTag) &&
        Objects.equals(this.fromAddress, getEmailTrackingDetailsRequest.fromAddress) &&
        Objects.equals(this.toAddress, getEmailTrackingDetailsRequest.toAddress) &&
        Objects.equals(this.ccAddress, getEmailTrackingDetailsRequest.ccAddress) &&
        Objects.equals(this.templateId, getEmailTrackingDetailsRequest.templateId) &&
        Objects.equals(this.paginationIn, getEmailTrackingDetailsRequest.paginationIn) &&
        super.equals(o);
  }*/

  public int hashCode() {
    return Objects.hash(dateFrom, dateTo, emailTag, fromAddress, toAddress, ccAddress, templateId, paginationIn, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetEmailTrackingDetailsRequest {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    dateFrom: ").append(toIndentedString(dateFrom)).append("\n");
    sb.append("    dateTo: ").append(toIndentedString(dateTo)).append("\n");
    sb.append("    emailTag: ").append(toIndentedString(emailTag)).append("\n");
    sb.append("    fromAddress: ").append(toIndentedString(fromAddress)).append("\n");
    sb.append("    toAddress: ").append(toIndentedString(toAddress)).append("\n");
    sb.append("    ccAddress: ").append(toIndentedString(ccAddress)).append("\n");
    sb.append("    templateId: ").append(toIndentedString(templateId)).append("\n");
    sb.append("    paginationIn: ").append(toIndentedString(paginationIn)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

