/*
 * Customer Reliability
 *  <b>Customer Reliability</b>  
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.CustomerData;
import org.joda.time.LocalDate;

/**
 * IndividualCompanyData
 */

public class IndividualCompanyData {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("surname")
  private String surname = null;

  @JsonProperty("fiscalCode")
  private String fiscalCode = null;

  @JsonProperty("sex")
  private String sex = null;

  @JsonProperty("birthDate")
  private LocalDate birthDate = null;

  @JsonProperty("birthCity")
  private String birthCity = null;

  @JsonProperty("birthProvince")
  private String birthProvince = null;

  @JsonProperty("birthNation")
  private String birthNation = null;

  @JsonProperty("citizenship")
  private String citizenship = null;

  @JsonProperty("companyName")
  private String companyName = null;

  @JsonProperty("reaCode")
  private String reaCode = null;

  @JsonProperty("cciaaProvince")
  private String cciaaProvince = null;

  public IndividualCompanyData name(String name) {
    this.name = name;
    return this;
  }

   /**
   * name of the card owner
   * @return name
  **/
  @ApiModelProperty(example = "Mario", value = "name of the card owner")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public IndividualCompanyData surname(String surname) {
    this.surname = surname;
    return this;
  }

   /**
   * surname of the card owner
   * @return surname
  **/
  @ApiModelProperty(example = "Rossi", value = "surname of the card owner")
  public String getSurname() {
    return surname;
  }

  public void setSurname(String surname) {
    this.surname = surname;
  }

  public IndividualCompanyData fiscalCode(String fiscalCode) {
    this.fiscalCode = fiscalCode;
    return this;
  }

   /**
   * company fiscal code
   * @return fiscalCode
  **/
  @ApiModelProperty(example = "2.403510924E9", value = "company fiscal code")
  public String getFiscalCode() {
    return fiscalCode;
  }

  public void setFiscalCode(String fiscalCode) {
    this.fiscalCode = fiscalCode;
  }

  public IndividualCompanyData sex(String sex) {
    this.sex = sex;
    return this;
  }

   /**
   * sex of card owner [F,M]
   * @return sex
  **/
  @ApiModelProperty(example = "M", value = "sex of card owner [F,M]")
  public String getSex() {
    return sex;
  }

  public void setSex(String sex) {
    this.sex = sex;
  }

  public IndividualCompanyData birthDate(LocalDate birthDate) {
    this.birthDate = birthDate;
    return this;
  }

   /**
   * card owner&#39;s date of birth
   * @return birthDate
  **/
  @ApiModelProperty(example = "2000-10-02", value = "card owner's date of birth")
  public LocalDate getBirthDate() {
    return birthDate;
  }

  public void setBirthDate(LocalDate birthDate) {
    this.birthDate = birthDate;
  }

  public IndividualCompanyData birthCity(String birthCity) {
    this.birthCity = birthCity;
    return this;
  }

   /**
   * card owner&#39;s city of birth
   * @return birthCity
  **/
  @ApiModelProperty(example = "Sesto San Giovanni", value = "card owner's city of birth")
  public String getBirthCity() {
    return birthCity;
  }

  public void setBirthCity(String birthCity) {
    this.birthCity = birthCity;
  }

  public IndividualCompanyData birthProvince(String birthProvince) {
    this.birthProvince = birthProvince;
    return this;
  }

   /**
   * card owner&#39;s province of birth (only italian customers)
   * @return birthProvince
  **/
  @ApiModelProperty(example = "MI", value = "card owner's province of birth (only italian customers)")
  public String getBirthProvince() {
    return birthProvince;
  }

  public void setBirthProvince(String birthProvince) {
    this.birthProvince = birthProvince;
  }

  public IndividualCompanyData birthNation(String birthNation) {
    this.birthNation = birthNation;
    return this;
  }

   /**
   * card owner&#39;s nation of birth
   * @return birthNation
  **/
  @ApiModelProperty(example = "Italy", value = "card owner's nation of birth")
  public String getBirthNation() {
    return birthNation;
  }

  public void setBirthNation(String birthNation) {
    this.birthNation = birthNation;
  }

  public IndividualCompanyData citizenship(String citizenship) {
    this.citizenship = citizenship;
    return this;
  }

   /**
   * citizenship
   * @return citizenship
  **/
  @ApiModelProperty(value = "citizenship")
  public String getCitizenship() {
    return citizenship;
  }

  public void setCitizenship(String citizenship) {
    this.citizenship = citizenship;
  }

  public IndividualCompanyData companyName(String companyName) {
    this.companyName = companyName;
    return this;
  }

   /**
   * company companyName
   * @return companyName
  **/
  @ApiModelProperty(example = "AIR TRADING", value = "company companyName")
  public String getCompanyName() {
    return companyName;
  }

  public void setCompanyName(String companyName) {
    this.companyName = companyName;
  }

  public IndividualCompanyData reaCode(String reaCode) {
    this.reaCode = reaCode;
    return this;
  }

   /**
   * company rea code
   * @return reaCode
  **/
  @ApiModelProperty(example = "1607692", value = "company rea code")
  public String getReaCode() {
    return reaCode;
  }

  public void setReaCode(String reaCode) {
    this.reaCode = reaCode;
  }

  public IndividualCompanyData cciaaProvince(String cciaaProvince) {
    this.cciaaProvince = cciaaProvince;
    return this;
  }

   /**
   * cciaa province of company
   * @return cciaaProvince
  **/
  @ApiModelProperty(example = "MI", value = "cciaa province of company")
  public String getCciaaProvince() {
    return cciaaProvince;
  }

  public void setCciaaProvince(String cciaaProvince) {
    this.cciaaProvince = cciaaProvince;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IndividualCompanyData individualCompanyData = (IndividualCompanyData) o;
    return Objects.equals(this.name, individualCompanyData.name) &&
        Objects.equals(this.surname, individualCompanyData.surname) &&
        Objects.equals(this.fiscalCode, individualCompanyData.fiscalCode) &&
        Objects.equals(this.sex, individualCompanyData.sex) &&
        Objects.equals(this.birthDate, individualCompanyData.birthDate) &&
        Objects.equals(this.birthCity, individualCompanyData.birthCity) &&
        Objects.equals(this.birthProvince, individualCompanyData.birthProvince) &&
        Objects.equals(this.birthNation, individualCompanyData.birthNation) &&
        Objects.equals(this.citizenship, individualCompanyData.citizenship) &&
        Objects.equals(this.companyName, individualCompanyData.companyName) &&
        Objects.equals(this.reaCode, individualCompanyData.reaCode) &&
        Objects.equals(this.cciaaProvince, individualCompanyData.cciaaProvince);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, surname, fiscalCode, sex, birthDate, birthCity, birthProvince, birthNation, citizenship, companyName, reaCode, cciaaProvince);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IndividualCompanyData {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    surname: ").append(toIndentedString(surname)).append("\n");
    sb.append("    fiscalCode: ").append(toIndentedString(fiscalCode)).append("\n");
    sb.append("    sex: ").append(toIndentedString(sex)).append("\n");
    sb.append("    birthDate: ").append(toIndentedString(birthDate)).append("\n");
    sb.append("    birthCity: ").append(toIndentedString(birthCity)).append("\n");
    sb.append("    birthProvince: ").append(toIndentedString(birthProvince)).append("\n");
    sb.append("    birthNation: ").append(toIndentedString(birthNation)).append("\n");
    sb.append("    citizenship: ").append(toIndentedString(citizenship)).append("\n");
    sb.append("    companyName: ").append(toIndentedString(companyName)).append("\n");
    sb.append("    reaCode: ").append(toIndentedString(reaCode)).append("\n");
    sb.append("    cciaaProvince: ").append(toIndentedString(cciaaProvince)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

