/*
 * Customer Reliability
 *  <b>Customer Reliability</b>  
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;

/**
 * administrative mandate
 */
@ApiModel(description = "administrative mandate")

public class Mandate {
  @JsonProperty("code")
  private BigDecimal code = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("startDate")
  private String startDate = null;

  @JsonProperty("endDate")
  private String endDate = null;

  public Mandate code(BigDecimal code) {
    this.code = code;
    return this;
  }

   /**
   * code of admin mandate
   * @return code
  **/
  @ApiModelProperty(example = "23.78", value = "code of admin mandate")
  public BigDecimal getCode() {
    return code;
  }

  public void setCode(BigDecimal code) {
    this.code = code;
  }

  public Mandate description(String description) {
    this.description = description;
    return this;
  }

   /**
   * description of admin mandate
   * @return description
  **/
  @ApiModelProperty(example = "EUR", value = "description of admin mandate")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Mandate startDate(String startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * start date of admin mandate
   * @return startDate
  **/
  @ApiModelProperty(value = "start date of admin mandate")
  public String getStartDate() {
    return startDate;
  }

  public void setStartDate(String startDate) {
    this.startDate = startDate;
  }

  public Mandate endDate(String endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * start date of admin mandate
   * @return endDate
  **/
  @ApiModelProperty(value = "start date of admin mandate")
  public String getEndDate() {
    return endDate;
  }

  public void setEndDate(String endDate) {
    this.endDate = endDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Mandate mandate = (Mandate) o;
    return Objects.equals(this.code, mandate.code) &&
        Objects.equals(this.description, mandate.description) &&
        Objects.equals(this.startDate, mandate.startDate) &&
        Objects.equals(this.endDate, mandate.endDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, description, startDate, endDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Mandate {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

