/*
 * Notification API
 * <b>Notification</b>  
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.PaginationIn;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * PaginationOut
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-05T15:49:18.314Z")
public class PaginationOut {
  @SerializedName("currentPage")
  private PaginationIn currentPage = null;

  @SerializedName("totPages")
  private BigDecimal totPages = null;

  public PaginationOut currentPage(PaginationIn currentPage) {
    this.currentPage = currentPage;
    return this;
  }

   /**
   * Get currentPage
   * @return currentPage
  **/
  @ApiModelProperty(required = true, value = "")
  public PaginationIn getCurrentPage() {
    return currentPage;
  }

  public void setCurrentPage(PaginationIn currentPage) {
    this.currentPage = currentPage;
  }

  public PaginationOut totPages(BigDecimal totPages) {
    this.totPages = totPages;
    return this;
  }

   /**
   * total number of page
   * @return totPages
  **/
  @ApiModelProperty(required = true, value = "total number of page")
  public BigDecimal getTotPages() {
    return totPages;
  }

  public void setTotPages(BigDecimal totPages) {
    this.totPages = totPages;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaginationOut paginationOut = (PaginationOut) o;
    return Objects.equals(this.currentPage, paginationOut.currentPage) &&
        Objects.equals(this.totPages, paginationOut.totPages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currentPage, totPages);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaginationOut {\n");
    
    sb.append("    currentPage: ").append(toIndentedString(currentPage)).append("\n");
    sb.append("    totPages: ").append(toIndentedString(totPages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

