/*
 * Notification API
 * <b>Notification</b>  
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.BaseRequest;
import io.swagger.client.model.TemplateValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * SendPushRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-05T15:49:18.314Z")
public class SendPushRequest extends BaseRequest {
  @SerializedName("deviceID")
  private String deviceID = null;

  @SerializedName("fiscalCode")
  private String fiscalCode = null;

  @SerializedName("templateId")
  private String templateId = null;

  @SerializedName("parameters")
  private List<TemplateValue> parameters = null;

  public SendPushRequest deviceID(String deviceID) {
    this.deviceID = deviceID;
    return this;
  }

   /**
   * Get deviceID
   * @return deviceID
  **/
  @ApiModelProperty(value = "")
  public String getDeviceID() {
    return deviceID;
  }

  public void setDeviceID(String deviceID) {
    this.deviceID = deviceID;
  }

  public SendPushRequest fiscalCode(String fiscalCode) {
    this.fiscalCode = fiscalCode;
    return this;
  }

   /**
   * Get fiscalCode
   * @return fiscalCode
  **/
  @ApiModelProperty(required = true, value = "")
  public String getFiscalCode() {
    return fiscalCode;
  }

  public void setFiscalCode(String fiscalCode) {
    this.fiscalCode = fiscalCode;
  }

  public SendPushRequest templateId(String templateId) {
    this.templateId = templateId;
    return this;
  }

   /**
   * Get templateId
   * @return templateId
  **/
  @ApiModelProperty(required = true, value = "")
  public String getTemplateId() {
    return templateId;
  }

  public void setTemplateId(String templateId) {
    this.templateId = templateId;
  }

  public SendPushRequest parameters(List<TemplateValue> parameters) {
    this.parameters = parameters;
    return this;
  }

  public SendPushRequest addParametersItem(TemplateValue parametersItem) {
    if (this.parameters == null) {
      this.parameters = new ArrayList<TemplateValue>();
    }
    this.parameters.add(parametersItem);
    return this;
  }

   /**
   * Get parameters
   * @return parameters
  **/
  @ApiModelProperty(value = "")
  public List<TemplateValue> getParameters() {
    return parameters;
  }

  public void setParameters(List<TemplateValue> parameters) {
    this.parameters = parameters;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SendPushRequest sendPushRequest = (SendPushRequest) o;
    return Objects.equals(this.deviceID, sendPushRequest.deviceID) &&
        Objects.equals(this.fiscalCode, sendPushRequest.fiscalCode) &&
        Objects.equals(this.templateId, sendPushRequest.templateId) &&
        Objects.equals(this.parameters, sendPushRequest.parameters) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deviceID, fiscalCode, templateId, parameters, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SendPushRequest {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    deviceID: ").append(toIndentedString(deviceID)).append("\n");
    sb.append("    fiscalCode: ").append(toIndentedString(fiscalCode)).append("\n");
    sb.append("    templateId: ").append(toIndentedString(templateId)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

