/*
 * Customer Reliability
 *  <b>Customer Reliability</b>  
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.BaseResponse;
import io.swagger.client.model.ErrorResult;
import io.swagger.client.model.FraudRiskAlert;
import io.swagger.client.model.FraudRiskAnalyserResult;
import io.swagger.client.model.ProfilingAlerts;
import io.swagger.client.model.Result;
import java.util.ArrayList;
import java.util.List;

/**
 * VerifyCustomerReliabilityResponse
 */

public class VerifyCustomerReliabilityResponse {
  @JsonProperty("result")
  private Result result = null;

  @JsonProperty("fraudRiskAlerts")
  private List<FraudRiskAlert> fraudRiskAlerts = null;

  @JsonProperty("fraudRiskAnalyserScore")
  private String fraudRiskAnalyserScore = null;

  @JsonProperty("fraudRiskAnalyserResult")
  private FraudRiskAnalyserResult fraudRiskAnalyserResult = null;

  @JsonProperty("messageId")
  private String messageId = null;

  @JsonProperty("registryVerificationId")
  private String registryVerificationId = null;

  @JsonProperty("fraudRiskErrors")
  private List<ErrorResult> fraudRiskErrors = null;

  @JsonProperty("fraudRiskProfilingAlerts")
  private List<ProfilingAlerts> fraudRiskProfilingAlerts = null;

  public VerifyCustomerReliabilityResponse result(Result result) {
    this.result = result;
    return this;
  }

   /**
   * Get result
   * @return result
  **/
  @ApiModelProperty(value = "")
  public Result getResult() {
    return result;
  }

  public void setResult(Result result) {
    this.result = result;
  }

  public VerifyCustomerReliabilityResponse fraudRiskAlerts(List<FraudRiskAlert> fraudRiskAlerts) {
    this.fraudRiskAlerts = fraudRiskAlerts;
    return this;
  }

  public VerifyCustomerReliabilityResponse addFraudRiskAlertsItem(FraudRiskAlert fraudRiskAlertsItem) {
    if (this.fraudRiskAlerts == null) {
      this.fraudRiskAlerts = new ArrayList<>();
    }
    this.fraudRiskAlerts.add(fraudRiskAlertsItem);
    return this;
  }

   /**
   * Get fraudRiskAlerts
   * @return fraudRiskAlerts
  **/
  @ApiModelProperty(value = "")
  public List<FraudRiskAlert> getFraudRiskAlerts() {
    return fraudRiskAlerts;
  }

  public void setFraudRiskAlerts(List<FraudRiskAlert> fraudRiskAlerts) {
    this.fraudRiskAlerts = fraudRiskAlerts;
  }

  public VerifyCustomerReliabilityResponse fraudRiskAnalyserScore(String fraudRiskAnalyserScore) {
    this.fraudRiskAnalyserScore = fraudRiskAnalyserScore;
    return this;
  }

   /**
   * score from the fraudRiskAnalyser
   * @return fraudRiskAnalyserScore
  **/
  @ApiModelProperty(value = "score from the fraudRiskAnalyser")
  public String getFraudRiskAnalyserScore() {
    return fraudRiskAnalyserScore;
  }

  public void setFraudRiskAnalyserScore(String fraudRiskAnalyserScore) {
    this.fraudRiskAnalyserScore = fraudRiskAnalyserScore;
  }

  public VerifyCustomerReliabilityResponse fraudRiskAnalyserResult(FraudRiskAnalyserResult fraudRiskAnalyserResult) {
    this.fraudRiskAnalyserResult = fraudRiskAnalyserResult;
    return this;
  }

   /**
   * Get fraudRiskAnalyserResult
   * @return fraudRiskAnalyserResult
  **/
  @ApiModelProperty(value = "")
  public FraudRiskAnalyserResult getFraudRiskAnalyserResult() {
    return fraudRiskAnalyserResult;
  }

  public void setFraudRiskAnalyserResult(FraudRiskAnalyserResult fraudRiskAnalyserResult) {
    this.fraudRiskAnalyserResult = fraudRiskAnalyserResult;
  }

  public VerifyCustomerReliabilityResponse messageId(String messageId) {
    this.messageId = messageId;
    return this;
  }

   /**
   * message id
   * @return messageId
  **/
  @ApiModelProperty(value = "message id")
  public String getMessageId() {
    return messageId;
  }

  public void setMessageId(String messageId) {
    this.messageId = messageId;
  }

  public VerifyCustomerReliabilityResponse registryVerificationId(String registryVerificationId) {
    this.registryVerificationId = registryVerificationId;
    return this;
  }

   /**
   * id stored in db
   * @return registryVerificationId
  **/
  @ApiModelProperty(value = "id stored in db")
  public String getRegistryVerificationId() {
    return registryVerificationId;
  }

  public void setRegistryVerificationId(String registryVerificationId) {
    this.registryVerificationId = registryVerificationId;
  }

  public VerifyCustomerReliabilityResponse fraudRiskErrors(List<ErrorResult> fraudRiskErrors) {
    this.fraudRiskErrors = fraudRiskErrors;
    return this;
  }

  public VerifyCustomerReliabilityResponse addFraudRiskErrorsItem(ErrorResult fraudRiskErrorsItem) {
    if (this.fraudRiskErrors == null) {
      this.fraudRiskErrors = new ArrayList<>();
    }
    this.fraudRiskErrors.add(fraudRiskErrorsItem);
    return this;
  }

   /**
   * Get fraudRiskErrors
   * @return fraudRiskErrors
  **/
  @ApiModelProperty(value = "")
  public List<ErrorResult> getFraudRiskErrors() {
    return fraudRiskErrors;
  }

  public void setFraudRiskErrors(List<ErrorResult> fraudRiskErrors) {
    this.fraudRiskErrors = fraudRiskErrors;
  }

  public VerifyCustomerReliabilityResponse fraudRiskProfilingAlerts(List<ProfilingAlerts> fraudRiskProfilingAlerts) {
    this.fraudRiskProfilingAlerts = fraudRiskProfilingAlerts;
    return this;
  }

  public VerifyCustomerReliabilityResponse addFraudRiskProfilingAlertsItem(ProfilingAlerts fraudRiskProfilingAlertsItem) {
    if (this.fraudRiskProfilingAlerts == null) {
      this.fraudRiskProfilingAlerts = new ArrayList<>();
    }
    this.fraudRiskProfilingAlerts.add(fraudRiskProfilingAlertsItem);
    return this;
  }

   /**
   * Get fraudRiskProfilingAlerts
   * @return fraudRiskProfilingAlerts
  **/
  @ApiModelProperty(value = "")
  public List<ProfilingAlerts> getFraudRiskProfilingAlerts() {
    return fraudRiskProfilingAlerts;
  }

  public void setFraudRiskProfilingAlerts(List<ProfilingAlerts> fraudRiskProfilingAlerts) {
    this.fraudRiskProfilingAlerts = fraudRiskProfilingAlerts;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VerifyCustomerReliabilityResponse verifyCustomerReliabilityResponse = (VerifyCustomerReliabilityResponse) o;
    return Objects.equals(this.result, verifyCustomerReliabilityResponse.result) &&
        Objects.equals(this.fraudRiskAlerts, verifyCustomerReliabilityResponse.fraudRiskAlerts) &&
        Objects.equals(this.fraudRiskAnalyserScore, verifyCustomerReliabilityResponse.fraudRiskAnalyserScore) &&
        Objects.equals(this.fraudRiskAnalyserResult, verifyCustomerReliabilityResponse.fraudRiskAnalyserResult) &&
        Objects.equals(this.messageId, verifyCustomerReliabilityResponse.messageId) &&
        Objects.equals(this.registryVerificationId, verifyCustomerReliabilityResponse.registryVerificationId) &&
        Objects.equals(this.fraudRiskErrors, verifyCustomerReliabilityResponse.fraudRiskErrors) &&
        Objects.equals(this.fraudRiskProfilingAlerts, verifyCustomerReliabilityResponse.fraudRiskProfilingAlerts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(result, fraudRiskAlerts, fraudRiskAnalyserScore, fraudRiskAnalyserResult, messageId, registryVerificationId, fraudRiskErrors, fraudRiskProfilingAlerts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VerifyCustomerReliabilityResponse {\n");
    
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    fraudRiskAlerts: ").append(toIndentedString(fraudRiskAlerts)).append("\n");
    sb.append("    fraudRiskAnalyserScore: ").append(toIndentedString(fraudRiskAnalyserScore)).append("\n");
    sb.append("    fraudRiskAnalyserResult: ").append(toIndentedString(fraudRiskAnalyserResult)).append("\n");
    sb.append("    messageId: ").append(toIndentedString(messageId)).append("\n");
    sb.append("    registryVerificationId: ").append(toIndentedString(registryVerificationId)).append("\n");
    sb.append("    fraudRiskErrors: ").append(toIndentedString(fraudRiskErrors)).append("\n");
    sb.append("    fraudRiskProfilingAlerts: ").append(toIndentedString(fraudRiskProfilingAlerts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

